// generated from rv32ima_sv32_linux source allowlist; do not edit
+incdir+rtl/profiles/rv32ima_sv32_linux
+incdir+sim/include
+define+NPC_USE_DPI
+define+NPC_DPI_MEM_LATENCY=0
+define+NPC_DPI_CSR_UNDEFINE
+define+NPC_M_EXTENSION
+define+NPC_MISALIGNED_DATA=1
+define+NPC_BRANCH_PRED
+define+NPC_BTB_ENTRIES=128
+define+NPC_BHT_ENTRIES=128
+define+NPC_BHR_BITS=8
+define+NPC_IF_HIT_PIPELINE
+define+NPC_LSU_HIT_PIPELINE
+define+NPC_LSU_LOAD_BYPASS
+define+NPC_EX_MEM_SKID
+define+NPC_STORE_BUFFER_ENABLE
+define+NPC_STORE_BUFFER_ENTRIES=2
+define+NPC_FAST_MUL
+define+NPC_FAST_MUL_LATENCY=2
+define+NPC_DCACHE_HIT_OPT
+define+NPC_DCACHE_WRITE_BACK=1
+define+NPC_DCACHE_WRITE_ALLOCATE=0
+define+NPC_HAS_MMU=1
+define+NPC_HAS_ITLB=1
+define+NPC_HAS_DTLB=1
+define+NPC_ITLB_ENTRIES=16
+define+NPC_DTLB_ENTRIES=16
rtl/profiles/rv32ima_sv32_linux/ALU.v
rtl/profiles/rv32ima_sv32_linux/BranchCond.v
rtl/profiles/rv32ima_sv32_linux/ContrGen.v
rtl/profiles/rv32ima_sv32_linux/ImmGen.v
rtl/profiles/rv32ima_sv32_linux/MuxKey.v
rtl/profiles/rv32ima_sv32_linux/MuxKeyInternal.v
rtl/profiles/rv32ima_sv32_linux/MuxKeyWithDefault.v
rtl/profiles/rv32ima_sv32_linux/PCAdder.v
rtl/profiles/rv32ima_sv32_linux/Reg.v
rtl/profiles/rv32ima_sv32_linux/RegisterFile.v
rtl/profiles/rv32ima_sv32_linux/cache/DCache.v
rtl/profiles/rv32ima_sv32_linux/cache/ICache.v
rtl/profiles/rv32ima_sv32_linux/csr/CsrContrGen.v
rtl/profiles/rv32ima_sv32_linux/csr/CsrRegisterFile.v
rtl/profiles/rv32ima_sv32_linux/csr/PrivCsrRegs.v
rtl/profiles/rv32ima_sv32_linux/csr/TrapCtrl.v
rtl/profiles/rv32ima_sv32_linux/frontend/InstrFetch.v
rtl/profiles/rv32ima_sv32_linux/frontend/Sv32FrontendPipe.v
rtl/profiles/rv32ima_sv32_linux/frontend/Sv32ICacheBridge.v
rtl/profiles/rv32ima_sv32_linux/frontend/Sv32IFetchPipe.v
rtl/profiles/rv32ima_sv32_linux/lsu/AclintTimer.v
rtl/profiles/rv32ima_sv32_linux/lsu/AxiPmemBridge.v
rtl/profiles/rv32ima_sv32_linux/lsu/DCacheMmioMux.v
rtl/profiles/rv32ima_sv32_linux/lsu/DataMem.v
rtl/profiles/rv32ima_sv32_linux/lsu/SimPmemBridge.v
rtl/profiles/rv32ima_sv32_linux/lsu/Sv32DCacheBridge.v
rtl/profiles/rv32ima_sv32_linux/lsu/Sv32LSUPipe.v
rtl/profiles/rv32ima_sv32_linux/mdu/Mdu.v
rtl/profiles/rv32ima_sv32_linux/mmu/Sv32Tlb.v
rtl/profiles/rv32ima_sv32_linux/pipeline/ex_stage.v
rtl/profiles/rv32ima_sv32_linux/pipeline/id_stage.v
rtl/profiles/rv32ima_sv32_linux/pipeline/if_stage.v
rtl/profiles/rv32ima_sv32_linux/pipeline/mem_stage.v
rtl/profiles/rv32ima_sv32_linux/pipeline/wb_stage.v
rtl/profiles/rv32ima_sv32_linux/stat/BranchStat.v
rtl/profiles/rv32ima_sv32_linux/stat/CacheStat.v
rtl/profiles/rv32ima_sv32_linux/stat/HitPathStat.v
rtl/profiles/rv32ima_sv32_linux/stat/InstrStat.v
rtl/profiles/rv32ima_sv32_linux/stat/MMUStat.v
rtl/profiles/rv32ima_sv32_linux/stat/PipeStat.v
rtl/profiles/rv32ima_sv32_linux/stat/PipelineCPIStat.v
rtl/profiles/rv32ima_sv32_linux/stat/StatCpiAttribution.v
rtl/profiles/rv32ima_sv32_linux/stat/StatFrontendBreakdown.v
rtl/profiles/rv32ima_sv32_linux/stat/StatHazardAfterForwarding.v
rtl/profiles/rv32ima_sv32_linux/stat/StatMemCpi.v
rtl/profiles/rv32ima_sv32_linux/stat/StatStageLatencyBreakdown.v
rtl/profiles/rv32ima_sv32_linux/top/CpuCorePipeline.v
rtl/profiles/rv32ima_sv32_linux/top/CpuDmemSubsystem.v
rtl/profiles/rv32ima_sv32_linux/top/CpuFrontendSubsystem.v
rtl/profiles/rv32ima_sv32_linux/top/CpuPerfMonitors.v
rtl/profiles/rv32ima_sv32_linux/top/cpu_top.v
rtl/wrappers/rv32ima_sv32_linux_sim_top.sv
