// generated from rv32im_single_perf source allowlist; do not edit
+incdir+rtl/profiles/rv32im_single_perf
+incdir+rtl/profiles/rv32im_single_perf/cpu_top
+incdir+sim/include
+define+NPC_USE_DPI
+define+NPC_DPI_MEM_LATENCY=2
+define+NPC_M_EXTENSION
rtl/profiles/rv32im_single_perf/ALU.v
rtl/profiles/rv32im_single_perf/AxiPmemBridge.v
rtl/profiles/rv32im_single_perf/BranchCond.v
rtl/profiles/rv32im_single_perf/BranchStat.v
rtl/profiles/rv32im_single_perf/CacheStat.v
rtl/profiles/rv32im_single_perf/ContrGen.v
rtl/profiles/rv32im_single_perf/CsrContrGen.v
rtl/profiles/rv32im_single_perf/CsrRegisterFile.v
rtl/profiles/rv32im_single_perf/DataMem.v
rtl/profiles/rv32im_single_perf/ImmGen.v
rtl/profiles/rv32im_single_perf/InstrFetch.v
rtl/profiles/rv32im_single_perf/InstrStat.v
rtl/profiles/rv32im_single_perf/Mdu.v
rtl/profiles/rv32im_single_perf/MuxKey.v
rtl/profiles/rv32im_single_perf/MuxKeyInternal.v
rtl/profiles/rv32im_single_perf/MuxKeyWithDefault.v
rtl/profiles/rv32im_single_perf/PCAdder.v
rtl/profiles/rv32im_single_perf/PipeStat.v
rtl/profiles/rv32im_single_perf/Reg.v
rtl/profiles/rv32im_single_perf/RegisterFile.v
rtl/profiles/rv32im_single_perf/SimPmemBridge.v
rtl/profiles/rv32im_single_perf/cache/CacheDataArray1R1W.v
rtl/profiles/rv32im_single_perf/cache/DCache.v
rtl/profiles/rv32im_single_perf/cache/ICache.v
rtl/profiles/rv32im_single_perf/cache/npc_cache_data_array_1r1w_512x32.v
rtl/profiles/rv32im_single_perf/cpu_top.v
rtl/profiles/rv32im_single_perf/cpu_top/ex_stage.v
rtl/profiles/rv32im_single_perf/cpu_top/id_stage.v
rtl/profiles/rv32im_single_perf/cpu_top/if_stage.v
rtl/profiles/rv32im_single_perf/cpu_top/include/bbus_core_defs.svh
rtl/profiles/rv32im_single_perf/cpu_top/mem_stage.v
rtl/profiles/rv32im_single_perf/cpu_top/pairing_unit.v
rtl/profiles/rv32im_single_perf/cpu_top/wb_stage.v
rtl/wrappers/rv32im_single_perf_sim_top.sv
