// Headless wrapper for the fixed dual-issue OoO Profile source set.
// The native ooo_npc_top owns its tagged DPI fetch/LSU transports, therefore
// this adapter only exposes the stable commit/halt/debug subset to Verilator.

`include "bbus_ooo_types.svh"

module npc_public_sim_top (
    input  logic        clk,
    input  logic        rst_n,
    input  logic [4:0]  debug_arch_idx,
    output logic        commit_valid,
    output logic [31:0] commit_pc,
    output logic [31:0] commit_instr,
    output logic [31:0] commit_nextpc,
    output logic        commit1_valid,
    output logic [31:0] commit1_pc,
    output logic [31:0] commit1_instr,
    output logic [31:0] commit1_nextpc,
    output logic        halt_valid,
    output logic [31:0] halt_pc,
    output logic [31:0] halt_instr,
    output logic [3:0]  halt_reason,
    output logic        idle,
    output logic [31:0] debug_arch_pc,
    output logic [31:0] debug_arch_gpr
);
    logic program_ready;
    // The 47 accepted Profile mechanisms are explicit here rather than being
    // inferred from a private Makefile.  All Oracle/reachability parameters
    // retain their disabled defaults.
    ooo_npc_top #(
        .USE_PMEM_IFETCH(1'b1),
        .ALU_LATENCY(1), .ALU1_LATENCY(1),
        .RAW_COMPLETION_WAKEUP_ENABLE(1'b1),
        .SAME_CYCLE_DEPENDENCY_FORWARDING_ENABLE(1'b1),
        .HEAD_LOAD_WRITEBACK_COMMIT_BYPASS_ENABLE(1'b1),
        .HEAD_ALU_WRITEBACK_COMMIT_BYPASS_ENABLE(1'b1),
        .HEAD_BRU_WRITEBACK_COMMIT_BYPASS_ENABLE(1'b1),
        .LOAD_RESPONSE_COMPLETION_BYPASS_ENABLE(1'b1),
        .LSU_REQUEST_FALLTHROUGH_ENABLE(1'b1),
        .PAIR_RAW_TO_FINAL_BYPASS_ENABLE(1'b1),
        .SERIAL_ORDINARY_COMPLETION_CONCURRENCY_ENABLE(1'b1),
        .SAME_CYCLE_DISPATCH_ISSUE_ENABLE(1'b1),
        .SAME_CYCLE_BRANCH_DISPATCH_ISSUE_ENABLE(1'b1),
        .BRANCH_ORDINARY_CONCURRENT_ISSUE_ENABLE(1'b1),
        .BRANCH_YOUNGER_ORDINARY_CONCURRENT_ISSUE_ENABLE(1'b1),
        .REGISTERED_BRU_DISPATCH_ORDINARY_ISSUE2_ENABLE(1'b1),
        .ISSUE_OPERAND_FALLTHROUGH_ENABLE(1'b1),
        .SLOT1_FINAL_WRITEBACK_COMMIT_BYPASS_ENABLE(1'b1),
        .BRANCH_ISSUE_FINAL_FALLTHROUGH_ENABLE(1'b1),
        .REGISTERED_BRANCH_ISSUE_FINAL_FALLTHROUGH_ENABLE(1'b1),
        .STORE_ISSUE_FINAL_FALLTHROUGH_ENABLE(1'b1),
        .MDU_MUL_COMPLETION_FALLTHROUGH_ENABLE(1'b1),
        .POSTED_STORE_RESPONSE_OWNERSHIP_ENABLE(1'b1),
        .POSTED_STORE_RESPONSE_PIPELINE_ENABLE(1'b1),
        .DUAL_POSTED_STORE_RESPONSE_OWNER_ENABLE(1'b1),
        .LOAD_TRANSACTION_DEPTH3_ENABLE(1'b1),
        .IFETCH_SAME_EDGE_RESPONSE_CAPTURE_ENABLE(1'b1),
        .DECODE_DISPATCH_FALLTHROUGH_ENABLE(1'b1),
        .FETCH_DECODE_FALLTHROUGH_ENABLE(1'b1),
        .FETCH_RESPONSE_CREDIT_TURNOVER_ENABLE(1'b1),
        .CORRECT_BRANCH_DUAL_RETIRE_ENABLE(1'b1),
        .YOUNGER_SLOT1_CONTROL_DUAL_RETIRE_ENABLE(1'b1),
        .POST_SELECTIVE_REDIRECT_COMMIT_ENABLE(1'b1),
        .SELECTIVE_TRANSACTION_REDIRECT_OVERLAP_ENABLE(1'b1),
        .STRONG_BRANCH_LINE_DELIVERY_ENABLE(1'b1),
        .DUAL_TRACE_SINK_ENABLE(1'b1),
        .TARGET_LINE_HIT_ENABLE(1'b1),
        .TARGET_LINE_ENTRY_COUNT(512),
        .TARGET_LINE_WAY_COUNT(1),
        .CONDITIONAL_PRED_ENTRIES(256),
        .CORRELATED_PREDICTOR_ENABLE(1'b1),
        .SAME_CYCLE_RAS_UPDATE_FORWARDING_ENABLE(1'b1),
        .RAS_SELF_FORWARD_EXCLUSION_ENABLE(1'b1),
        .SEQUENTIAL_LINE_HIT_ENABLE(1'b1),
        .BRANCH_WINDOW_LINE_DELIVERY_ENABLE(1'b1),
        .SPECULATIVE_STORE_DISPATCH_ENABLE(1'b1),
        .DATA_LINE_HIT_ENABLE(1'b1),
        .DATA_LINE_SAME_WORD_MISS_COALESCING_ENABLE(1'b1),
        .DATA_LINE_STORE_RESPONSE_UPDATE_ENABLE(1'b1),
        .DATA_LINE_COUNT(1024),
        .DATA_LINE_WAY_COUNT(1),
        .PIPE_PERF_ACCOUNTING_ENABLE(1'b0),
        .PIPE_PERF_OBSERVABILITY_ENABLE(1'b0),
        .STRUCTURAL_THROUGHPUT_ORACLE_ENABLE(1'b0),
        .SINGLETON_COALESCE_ORACLE_ENABLE(1'b0),
        .PARTIAL_PAIR_ORACLE_ENABLE(1'b0),
        .CACHED_CROSS_LINE_PAIR_ENABLE(1'b0),
        .CACHED_CROSS_LINE_ROLLING_CARRY_ENABLE(1'b1)
    ) u_cpu (
        .clk(clk), .rst_n(rst_n),
        .program_valid_i(1'b0), .program_pc_i(32'b0),
        .program_instr_i(32'b0), .program_ready_o(program_ready),
        .commit_ready_i(1'b1),
        .commit_valid_o(commit_valid),
        .commit_pc_o(commit_pc), .commit_instr_o(commit_instr),
        .commit_nextpc_o(commit_nextpc),
        .commit1_valid_o(commit1_valid),
        .commit1_pc_o(commit1_pc), .commit1_instr_o(commit1_instr),
        .commit1_nextpc_o(commit1_nextpc),
        .unsupported_seen_o(), .unsupported_pc_o(), .unsupported_instr_o(),
        .shadow_idle_o(idle), .halt_valid_o(halt_valid),
        .halt_pc_o(halt_pc), .halt_instr_o(halt_instr),
        .halt_reason_o(halt_reason),
        .debug_arch_idx_i(debug_arch_idx),
        .debug_arch_gpr_o(debug_arch_gpr), .debug_arch_pc_o(debug_arch_pc)
    );
endmodule
