`ifndef BBUS_OOO_CFG_SVH
`define BBUS_OOO_CFG_SVH

`define BBUS_OOO_XLEN 32
`define BBUS_OOO_ARCH_REGS 32
`define BBUS_OOO_PHYS_REGS 64
`define BBUS_OOO_ROB_ENTRIES 8
`define BBUS_OOO_ROB_GEN_W 2

`define BBUS_OOO_ARCH_REG_W 5
`define BBUS_OOO_PHYS_REG_W 6
`define BBUS_OOO_ROB_IDX_W 3

`define BBUS_OOO_PHYS_ZERO 6'd0

`ifndef NPC_OOO_DISPATCH_WIDTH
`define NPC_OOO_DISPATCH_WIDTH 1
`endif
`ifndef NPC_OOO_COMMIT_WIDTH
`define NPC_OOO_COMMIT_WIDTH 1
`endif
`ifndef NPC_OOO_DISPATCH2_TEST_LIMIT_ROB_FREE
`define NPC_OOO_DISPATCH2_TEST_LIMIT_ROB_FREE 0
`endif
`ifndef NPC_OOO_DISPATCH2_TEST_LIMIT_IQ_FREE
`define NPC_OOO_DISPATCH2_TEST_LIMIT_IQ_FREE 0
`endif
`ifndef NPC_OOO_DISPATCH2_TEST_LIMIT_FREELIST_FREE
`define NPC_OOO_DISPATCH2_TEST_LIMIT_FREELIST_FREE 0
`endif

`endif
