`timescale 1ns / 1ps

module CpuCorePipeline #(
    parameter integer BPU_BTB_ENTRIES = 128,
    parameter integer BPU_BHT_ENTRIES = 128,
    parameter integer BPU_BHR_BITS = 8,
    parameter [31:0] RESET_VECTOR = 32'h80000000
) (
    input clk,
    input rst_n,
    output ds_allowin,
    input stop_fetch,
    input store_buffer_drain_before_maint,
    input hold_fetch,
    input redirect_flush_valid,
    input stop_clear_valid,
    input [31:0] redirect_flush_pc,
    input bpu_update_valid,
    output [31:0] es_pc,
    input bpu_update_is_cond,
    output ex_branch_taken_actual,
    output [31:0] es_nextpc,
    output [31:0] ex_branch_pred_pht_idx,
    output fs_to_ds_valid,
    output [31:0] fs_pc,
    output [31:0] fs_instr,
    output fs_exc_valid,
    output [31:0] fs_exc_cause,
    output [31:0] fs_exc_tval,
    output fs_pred_taken,
    output [31:0] fs_pred_target,
    output fs_pred_btb_hit,
    output fs_pred_btb_is_cond,
    output [1:0] fs_pred_bht_state,
    output [31:0] fs_pred_pht_idx,
    output if_stall,
    output ibus_req_valid_w,
    input ibus_req_ready,
    output [31:0] ibus_req_addr_w,
    output ibus_req_pred_taken,
    output [31:0] ibus_req_pred_target,
    output ibus_req_pred_btb_hit,
    output ibus_req_pred_btb_is_cond,
    output [1:0] ibus_req_pred_bht_state,
    output [31:0] ibus_req_pred_pht_idx,
    input ibus_resp_valid,
    output ibus_resp_ready_w,
    input [31:0] ibus_resp_data,
    input ibus_resp_exc_valid,
    input [31:0] ibus_resp_exc_cause,
    input [31:0] ibus_resp_exc_tval,
    output if_stat_fs_valid,
    output [1:0] if_stat_queue_count,
    output if_stat_fetch_room,
    output if_stat_req_fire,
    output if_stat_resp_fire,
    output if_stat_resp_accept,
    output if_stat_resp_drop,
    output if_stat_bypass_direct,
    output if_stat_waiting_resp,
    output if_stat_drop_resp,
    output if_stat_fs_pop,
    output if_stat_resp_enq,
    output if_stat_queue_full,
    output if_stat_resp_block,
    input [31:0] ibus_resp_pc,
    input [31:0] ibus_resp_seq,
    input [15:0] ibus_resp_epoch,
    input ibus_resp_pred_taken,
    input [31:0] ibus_resp_pred_target,
    input ibus_resp_pred_btb_hit,
    input ibus_resp_pred_btb_is_cond,
    input [1:0] ibus_resp_pred_bht_state,
    input [31:0] ibus_resp_pred_pht_idx,
    output ex_mispredict_flush_valid,
    output branch_stat_fetch_req_valid,
    output [31:0] branch_stat_fetch_req_pc,
    output branch_stat_fetch_accept_valid,
    output [31:0] branch_stat_fetch_accept_pc,
    output [31:0] branch_stat_fetch_accept_instr,
    output branch_stat_fetch_drop_valid,
    output branch_stat_fetch_drop_redirect,
    output [31:0] branch_stat_fetch_drop_pc,
    output [31:0] branch_stat_fetch_drop_instr,
    output [63:0] bpu_btb_lookup_count,
    output [63:0] bpu_btb_hit_count,
    output [63:0] bpu_btb_miss_count,
    output [63:0] bpu_bht_pred_taken_count,
    output [63:0] bpu_bht_pred_not_taken_count,
    output [63:0] bpu_btb_conflict_count,
    output [63:0] bpu_btb_update_count,
    output [63:0] bpu_btb_replace_count,
    output [63:0] bpu_bht_lookup_count,
    output [63:0] bpu_bht_update_count,
    output [63:0] bpu_bht_weak_taken_count,
    output [63:0] bpu_bht_weak_not_taken_count,
    output [63:0] bpu_bht_strong_taken_count,
    output [63:0] bpu_bht_strong_not_taken_count,
    output [31:0] bpu_bhr_value,
    input flush_id,
    output es_allowin,
    output ds_to_es_valid,
    output [4:0] rf_raddr1,
    input [31:0] rf_rdata1,
    output [4:0] rf_raddr2,
    input [31:0] rf_rdata2,
    output [11:0] csr_raddr,
    input [31:0] csr_rdata,
    output es_valid,
    output es_reg_wen,
    output [4:0] es_rd,
    output [1:0] es_csr_wen,
    output [11:0] es_csr_waddr1,
    output [11:0] es_csr_waddr2,
    output ms_valid,
    output ms_reg_wen,
    output [4:0] ms_rd,
    output [1:0] ms_csr_wen,
    output [11:0] ms_csr_waddr1,
    output [11:0] ms_csr_waddr2,
    output hidden_mreq_valid,
    output hidden_mreq_reg_wen,
    output [4:0] hidden_mreq_rd,
    output [1:0] hidden_mreq_csr_wen,
    output [11:0] hidden_mreq_csr_waddr1,
    output [11:0] hidden_mreq_csr_waddr2,
    output ws_valid,
    output [4:0] ws_rd,
    output ws_reg_wen,
    output [1:0] ws_csr_wen,
    output [11:0] ws_csr_waddr1,
    output [11:0] ws_csr_waddr2,
    output es_result_bypassable,
    input ms_alu_fwd_valid,
    input ms_load_bypass_valid,
    input [4:0] ms_load_bypass_rd,
    input ws_alu_fwd_valid,
    input ms_fwd_valid,
    input [31:0] ms_fwd_data,
    output [31:0] ds_pc,
    output [31:0] ds_instr,
    output ds_exc_valid,
    output [31:0] ds_exc_cause,
    output [31:0] ds_exc_tval,
    output [4:0] ds_rs1,
    output [4:0] ds_rs2,
    output [31:0] ds_src1,
    output [31:0] ds_src2,
    output ds_src1_from_prev_ex,
    output ds_src2_from_prev_ex,
    output ds_src1_from_prev_wb,
    output ds_src2_from_prev_wb,
    output ds_pred_taken,
    output [31:0] ds_pred_target,
    output ds_pred_btb_hit,
    output ds_pred_btb_is_cond,
    output [1:0] ds_pred_bht_state,
    output [31:0] ds_pred_pht_idx,
    output [31:0] ds_imm,
    output [31:0] ds_zimm,
    output [31:0] ds_scsr,
    output [4:0] ds_rd,
    output ds_reg_wen,
    output [2:0] ds_branch,
    output [1:0] ds_datatoreg,
    output [1:0] ds_mem_wr,
    output [2:0] ds_mem_op,
    output ds_atomic_en,
    output [3:0] ds_atomic_op,
    output [1:0] ds_alu_a_src,
    output [1:0] ds_alu_b_src,
    output [3:0] ds_alu_ctr,
    output [1:0] ds_csr_wen,
    output [11:0] ds_csr_waddr1,
    output [11:0] ds_csr_waddr2,
    output [1:0] ds_csr_wdata_src1,
    output ds_csr_wdata_src2,
    output ds_illegal,
    output ds_is_ebreak,
    output ds_stop_fetch,
    output ds_stage_block,
    output ds_stage_block_reg_hazard,
    output ds_stage_block_csr_hazard,
    output ds_stage_block_load_use,
    output ds_stage_block_ex_raw,
    output ds_stage_block_ms_raw,
    output ds_stage_block_hidden_raw,
    output ds_stat_uses_rs1,
    output ds_stat_uses_rs2,
    output ds_stat_rs1_match_es,
    output ds_stat_rs1_match_ms,
    output ds_stat_rs1_match_hidden,
    output ds_stat_rs1_match_ws,
    output ds_stat_rs2_match_es,
    output ds_stat_rs2_match_ms,
    output ds_stat_rs2_match_hidden,
    output ds_stat_rs2_match_ws,
    output ds_stat_csr_counter_hazard,
    output ds_stat_rs1_ex_alu_fwd,
    output ds_stat_rs2_ex_alu_fwd,
    output ds_stat_fwd_load_block,
    output ds_stat_fwd_csr_block,
    output ds_stat_fwd_kill_block,
`ifdef NPC_M_EXTENSION
    output ds_mdu_en,
    output [2:0] ds_mdu_op,
`else
    output ds_mdu_en_dummy,
    output [2:0] ds_mdu_op_dummy,
`endif
    input flush_ex,
    input ds_to_es_fire,
    output ms_allowin,
    output es_to_ms_valid,
    output [31:0] ws_rf_wdata,
    output [31:0] ms_aluout,
    output ms_fast_mul_stat,
    input [31:0] ms_load_bypass_data,
    input hidden_alu_fwd_valid,
    output [31:0] hidden_mreq_aluout,
    output hidden_mreq_fast_mul_stat,
    input ws_load_fwd_valid,
    output ws_fast_mul_stat,
    output [31:0] es_instr,
    output [1:0] es_datatoreg,
    output [1:0] es_mem_wr,
    output [2:0] es_mem_op,
    output es_atomic_en,
    output [3:0] es_atomic_op,
    output [31:0] es_aluout,
    output [31:0] es_mem_wdata,
    output [31:0] es_csr_read_data,
    output [31:0] es_csr_wdata1,
    output [31:0] es_csr_wdata2,
    output es_illegal,
    output es_exc_valid,
    output [31:0] es_exc_cause,
    output [31:0] es_exc_tval,
    output es_is_ebreak,
    output [2:0] es_branch,
    output [31:0] es_src1_value,
    output es_mem_fwd_dep,
    output atomic_alu_ready,
    output atomic_alu_req_valid,
    output [3:0] atomic_alu_op,
    output [31:0] atomic_alu_old,
    output [31:0] atomic_alu_rs2,
    output atomic_alu_resp_valid,
    output [31:0] atomic_alu_result,
    output es_stage_block,
    output es_stage_block_mdu_wait,
    output es_stage_block_redirect_wait,
    output es_stat_is_mdu,
    output es_stat_rs1_mem_alu_fwd,
    output es_stat_rs2_mem_alu_fwd,
    output es_stat_rs1_wb_fwd,
    output es_stat_rs2_wb_fwd,
    output es_stat_rs1_load_fwd,
    output es_stat_rs2_load_fwd,
    output [2:0] es_stat_mdu_op,
    output es_stat_mdu_req_fire,
    output es_stat_mdu_resp_valid,
    output es_stat_mdu_busy,
    output es_stat_mdu_result_ready,
    output es_stat_fast_mul,
    output es_stat_fast_mul_issue,
    output es_stat_fast_mul_resp_unused,
    output es_stat_fast_mul_kill,
    output es_stat_fast_mul_flush_drop,
    output es_stat_fast_mul_forward,
    output es_stat_fast_mul_stall_wait_ready,
    output es_stat_old_div_path,
    output es_stat_old_rem_path,
    output ex_flush_valid,
    output [31:0] ex_flush_pc,
    output [31:0] ex_mispredict_flush_pc,
    output ex_branch_pred_taken,
    output [31:0] ex_branch_pred_target,
    output ex_branch_pred_btb_hit,
    output ex_branch_pred_btb_is_cond,
    output [1:0] ex_branch_pred_bht_state,
    output ex_branch_target_mismatch,
    input flush_mem,
    output ws_allowin,
    output ms_to_ws_valid,
    input es_fast_mul_stat_to_mem,
    output [31:0] ms_pc,
    output [31:0] ms_instr,
    output [31:0] ms_nextpc,
    output [1:0] ms_datatoreg,
    output [2:0] ms_mem_op,
    output [31:0] ms_mem_rdata,
    output [31:0] ms_csr_read_data,
    output [31:0] ms_csr_wdata1,
    output [31:0] ms_csr_wdata2,
    output ms_illegal,
    output ms_exc_valid,
    output [31:0] ms_exc_cause,
    output [31:0] ms_exc_tval,
    output ms_is_ebreak,
    output [2:0] ms_branch,
    output [31:0] ms_src1_value,
    output ms_stage_block,
    output ms_stage_block_req_phase,
    output ms_stage_block_resp_phase,
    output ms_stage_block_load,
    output ms_stage_block_store,
    output ms_stage_block_req_load,
    output ms_stage_block_req_store,
    output ms_stage_block_resp_load,
    output ms_stage_block_resp_store,
    output ms_fast_req_fire_trace,
    output ms_slow_req_fire_trace,
    output ms_slow_req_fwd_dep_fire_trace,
    output ms_slow_req_nonfwd_fire_trace,
    output ms_stat_load_visible,
    output ms_stat_load_aligned,
    output ms_stat_load_result_ready,
    output ms_stat_load_fault,
    output ms_stat_load_signext_ready,
    output ms_stat_load_req_fire,
    output ms_stat_load_resp_valid,
    output ms_stat_load_resp_fire,
    output ms_stat_load_data_ready,
    output ms_stat_load_signext_data_ready,
    output ms_stat_load_to_wb_valid,
    output ms_stat_load_split_or_misaligned,
    output ms_stat_load_uncached,
    output ms_stat_load_atomic,
    output ms_stat_load_killed,
    output ms_stat_hidden_load,
    output ms_stat_load_store_block,
    output ms_stat_load_lsu_pending,
    output ms_stat_mreq_valid,
    output ms_stat_mreq_is_load,
    output ms_stat_mreq_is_store,
    output ms_stat_mreq_is_atomic,
    output ms_stat_mreq_need_mem,
    output ms_stat_mreq_fire,
    output ms_stat_mreq_misaligned,
    output ms_stat_mreq_split,
    output ms_stat_mreq_fault,
    output ms_stat_mreq_blocked_by_resp,
    output ms_stat_mresp_valid,
    output ms_stat_mresp_is_load,
    output ms_stat_mresp_is_store,
    output ms_stat_mresp_is_atomic,
    output ms_stat_mresp_resp_valid,
    output ms_stat_mresp_resp_fire,
    output ms_stat_mresp_split,
    output ms_stat_mresp_fault,
    output ms_stat_store_visible,
    output ms_stat_store_req_fire,
    output ms_stat_store_resp_valid,
    output ms_stat_store_resp_fire,
    output ms_stat_store_aligned,
    output ms_stat_store_fault,
    output ms_stat_store_split_or_misaligned,
    output ms_stat_store_uncached,
    output ms_stat_store_atomic,
    output ms_stat_store_killed,
    output ms_stat_store_buffer_safe,
    output ms_stat_store_resp_wait,
    output ms_stat_single_outstanding_wait,
    output ms_stat_uncached_wait,
    output ms_stat_writeback_wait,
    output [63:0] stat_exmem_skid_candidate,
    output [63:0] stat_exmem_skid_enqueue,
    output [63:0] stat_exmem_skid_dequeue,
    output [63:0] stat_exmem_skid_full_stall,
    output [63:0] stat_exmem_skid_flush_drop,
    output [63:0] stat_exmem_skid_blocked_not_safe,
    output [63:0] stat_exmem_skid_blocked_branch,
    output [63:0] stat_exmem_skid_blocked_mem,
    output [63:0] stat_exmem_skid_blocked_csr,
    output [63:0] stat_exmem_skid_blocked_exception,
    output [63:0] stat_exmem_skid_blocked_div,
    output [63:0] stat_exmem_skid_blocked_structural,
    output [63:0] stat_exmem_skid_hold_cycles,
    output [63:0] stat_exmem_skid_hold_mem_wait_cycles,
    output [63:0] stat_exmem_skid_dequeue_after_mem_release,
    output [63:0] stat_exmem_skid_dequeue_same_cycle_mem_release,
    output [63:0] stat_exmem_skid_dequeue_causes_wb_valid,
    output stat_exmem_skid_valid,
    output stat_exmem_skid_enqueue_fire,
    output stat_exmem_skid_dequeue_fire,
    output stat_exmem_skid_dequeue_commit_fire,
    output stat_exmem_skid_dequeue_to_mreq_fire,
    output stat_exmem_skid_mem_wait,
    output stat_exmem_skid_mem_release,
    output [1:0] hidden_mreq_datatoreg,
    output [1:0] hidden_mreq_mem_wr,
    output dbus_req_valid,
    input dbus_req_ready,
    output dbus_req_fast_ok,
    output dbus_req_fast_block_atomic,
    output dbus_req_fast_block_misaligned,
    output dbus_req_fast_block_exception,
    output dbus_req_fast_block_phase2,
    output dbus_req_fast_block_other,
    output dbus_req_write,
    output dbus_req_atomic,
    output dbus_req_store_bufferable,
    output [31:0] dbus_req_addr,
    output [31:0] dbus_req_wdata,
    output [3:0] dbus_req_wstrb,
    output [2:0] dbus_req_len,
    input dbus_resp_valid,
    output dbus_resp_ready,
    input [31:0] dbus_resp_data,
    input dbus_resp_exc_valid,
    input [31:0] dbus_resp_exc_cause,
    input [31:0] dbus_resp_exc_tval,
    output dbg_mem_mreq_valid,
    output dbg_mem_mresp_valid,
    output dbg_mem_skid_valid,
    output [31:0] dbg_mem_mreq_instr,
    output [31:0] dbg_mem_mresp_instr,
    output dbg_mem_mreq_need_mem,
    output dbg_mem_mreq_req_valid,
    output dbg_mem_mreq_mem_fire,
    output dbg_mem_mreq_nonmem_fire,
    output dbg_mem_mreq_consumed_eff,
    output dbg_mem_mresp_ready_go,
    output dbg_mem_mresp_commit_fire,
    output dbg_mem_old_mreq_allowin,
    output dbg_mem_mresp_atomic_en,
    output dbg_mem_mresp_split,
    output dbg_mem_mresp_phase1_amo_read,
    input wb_flush,
    output [31:0] ws_pc,
    output [31:0] ws_instr,
    output [31:0] ws_nextpc,
    output [1:0] ws_stat_datatoreg,
    output [2:0] ws_stat_mem_op,
    output [31:0] ws_csr_wdata1,
    output [31:0] ws_csr_wdata2,
    output ws_illegal,
    output ws_exc_valid,
    output [31:0] ws_exc_cause,
    output [31:0] ws_exc_tval,
    output ws_is_ebreak,
    output [2:0] ws_branch,
    output [31:0] ws_src1_value
);

    if_stage #(
        .BTB_ENTRIES(BPU_BTB_ENTRIES),
        .BHT_ENTRIES(BPU_BHT_ENTRIES),
        .BHR_BITS(BPU_BHR_BITS),
        .RESET_VECTOR(RESET_VECTOR)
    ) u_if_stage(
        .clk(clk),
        .rst_n(rst_n),
        .ds_allowin(ds_allowin),
        .stop_fetch(stop_fetch),
        .pause_fetch(store_buffer_drain_before_maint),
        .hold_fetch(hold_fetch),
        .redirect_flush(redirect_flush_valid),
        .stop_clear(stop_clear_valid),
        .flush_pc(redirect_flush_pc),
        .bpu_update_valid(bpu_update_valid),
        .bpu_update_pc(es_pc),
        .bpu_update_is_cond(bpu_update_is_cond),
        .bpu_update_taken(ex_branch_taken_actual),
        .bpu_update_target(es_nextpc),
        .bpu_update_pht_idx(ex_branch_pred_pht_idx),
        .fs_to_ds_valid(fs_to_ds_valid),
        .fs_pc(fs_pc),
        .fs_instr(fs_instr),
        .fs_exc_valid(fs_exc_valid),
        .fs_exc_cause(fs_exc_cause),
        .fs_exc_tval(fs_exc_tval),
        .fs_pred_taken(fs_pred_taken),
        .fs_pred_target(fs_pred_target),
        .fs_pred_btb_hit(fs_pred_btb_hit),
        .fs_pred_btb_is_cond(fs_pred_btb_is_cond),
        .fs_pred_bht_state(fs_pred_bht_state),
        .fs_pred_pht_idx(fs_pred_pht_idx),
        .if_stall(if_stall),
        .ibus_req_valid(ibus_req_valid_w),
        .ibus_req_ready(ibus_req_ready),
        .ibus_req_addr(ibus_req_addr_w),
        .ibus_req_pred_taken(ibus_req_pred_taken),
        .ibus_req_pred_target(ibus_req_pred_target),
        .ibus_req_pred_btb_hit(ibus_req_pred_btb_hit),
        .ibus_req_pred_btb_is_cond(ibus_req_pred_btb_is_cond),
        .ibus_req_pred_bht_state(ibus_req_pred_bht_state),
        .ibus_req_pred_pht_idx(ibus_req_pred_pht_idx),
        .ibus_resp_valid(ibus_resp_valid),
        .ibus_resp_ready(ibus_resp_ready_w),
        .ibus_resp_data(ibus_resp_data),
        .ibus_resp_exc_valid(ibus_resp_exc_valid),
        .ibus_resp_exc_cause(ibus_resp_exc_cause),
        .ibus_resp_exc_tval(ibus_resp_exc_tval)
`ifdef NPC_PIPE_STAT
        ,
        .if_stat_fs_valid(if_stat_fs_valid),
        .if_stat_queue_count(if_stat_queue_count),
        .if_stat_fetch_room(if_stat_fetch_room),
        .if_stat_req_fire(if_stat_req_fire),
        .if_stat_resp_fire(if_stat_resp_fire),
        .if_stat_resp_accept(if_stat_resp_accept),
        .if_stat_resp_drop(if_stat_resp_drop),
        .if_stat_bypass_direct(if_stat_bypass_direct),
        .if_stat_waiting_resp(if_stat_waiting_resp),
        .if_stat_drop_resp(if_stat_drop_resp),
        .if_stat_fs_pop(if_stat_fs_pop),
        .if_stat_resp_enq(if_stat_resp_enq),
        .if_stat_queue_full(if_stat_queue_full),
        .if_stat_resp_block(if_stat_resp_block)
`endif
`ifdef NPC_IF_HIT_PIPELINE
        ,
        .ibus_resp_pc(ibus_resp_pc),
        .ibus_resp_seq(ibus_resp_seq),
        .ibus_resp_epoch(ibus_resp_epoch),
        .ibus_resp_pred_taken(ibus_resp_pred_taken),
        .ibus_resp_pred_target(ibus_resp_pred_target),
        .ibus_resp_pred_btb_hit(ibus_resp_pred_btb_hit),
        .ibus_resp_pred_btb_is_cond(ibus_resp_pred_btb_is_cond),
        .ibus_resp_pred_bht_state(ibus_resp_pred_bht_state),
        .ibus_resp_pred_pht_idx(ibus_resp_pred_pht_idx)
`endif
`ifdef NPC_BRANCH_STAT
        ,
        .flush_trace_is_redirect(ex_mispredict_flush_valid),
        .fetch_req_trace_valid(branch_stat_fetch_req_valid),
        .fetch_req_trace_pc(branch_stat_fetch_req_pc),
        .fetch_accept_trace_valid(branch_stat_fetch_accept_valid),
        .fetch_accept_trace_pc(branch_stat_fetch_accept_pc),
        .fetch_accept_trace_instr(branch_stat_fetch_accept_instr),
        .fetch_drop_trace_valid(branch_stat_fetch_drop_valid),
        .fetch_drop_trace_redirect(branch_stat_fetch_drop_redirect),
        .fetch_drop_trace_pc(branch_stat_fetch_drop_pc),
        .fetch_drop_trace_instr(branch_stat_fetch_drop_instr),
        .bpu_btb_lookup_count(bpu_btb_lookup_count),
        .bpu_btb_hit_count(bpu_btb_hit_count),
        .bpu_btb_miss_count(bpu_btb_miss_count),
        .bpu_bht_pred_taken_count(bpu_bht_pred_taken_count),
        .bpu_bht_pred_not_taken_count(bpu_bht_pred_not_taken_count),
        .bpu_btb_conflict_count(bpu_btb_conflict_count),
        .bpu_btb_update_count(bpu_btb_update_count),
        .bpu_btb_replace_count(bpu_btb_replace_count),
        .bpu_bht_lookup_count(bpu_bht_lookup_count),
        .bpu_bht_update_count(bpu_bht_update_count),
        .bpu_bht_weak_taken_count(bpu_bht_weak_taken_count),
        .bpu_bht_weak_not_taken_count(bpu_bht_weak_not_taken_count),
        .bpu_bht_strong_taken_count(bpu_bht_strong_taken_count),
        .bpu_bht_strong_not_taken_count(bpu_bht_strong_not_taken_count),
        .bpu_bhr_value(bpu_bhr_value)
`endif
    );
    id_stage u_id_stage(
        .clk(clk),
        .rst_n(rst_n),
        .flush(flush_id),
        .fs_to_ds_valid(fs_to_ds_valid),
        .fs_pc(fs_pc),
        .fs_instr(fs_instr),
        .fs_exc_valid(fs_exc_valid),
        .fs_exc_cause(fs_exc_cause),
        .fs_exc_tval(fs_exc_tval),
        .fs_pred_taken(fs_pred_taken),
        .fs_pred_target(fs_pred_target),
        .fs_pred_btb_hit(fs_pred_btb_hit),
        .fs_pred_btb_is_cond(fs_pred_btb_is_cond),
        .fs_pred_bht_state(fs_pred_bht_state),
        .fs_pred_pht_idx(fs_pred_pht_idx),
        .ds_allowin(ds_allowin),
        .es_allowin(es_allowin),
        .ds_to_es_valid(ds_to_es_valid),
        .rf_raddr1(rf_raddr1),
        .rf_rdata1(rf_rdata1),
        .rf_raddr2(rf_raddr2),
        .rf_rdata2(rf_rdata2),
        .csr_raddr(csr_raddr),
        .csr_rdata(csr_rdata),
        .es_valid(es_valid),
        .es_reg_wen(es_reg_wen),
        .es_rd(es_rd),
        .es_csr_wen(es_csr_wen),
        .es_csr_waddr1(es_csr_waddr1),
        .es_csr_waddr2(es_csr_waddr2),
        .ms_valid(ms_valid),
        .ms_reg_wen(ms_reg_wen),
        .ms_rd(ms_rd),
        .ms_csr_wen(ms_csr_wen),
        .ms_csr_waddr1(ms_csr_waddr1),
        .ms_csr_waddr2(ms_csr_waddr2),
        .hidden_mreq_valid(hidden_mreq_valid),
        .hidden_mreq_reg_wen(hidden_mreq_reg_wen),
        .hidden_mreq_rd(hidden_mreq_rd),
        .hidden_mreq_csr_wen(hidden_mreq_csr_wen),
        .hidden_mreq_csr_waddr1(hidden_mreq_csr_waddr1),
        .hidden_mreq_csr_waddr2(hidden_mreq_csr_waddr2),
        .ws_valid(ws_valid),
        .ws_rd(ws_rd),
        .ws_reg_wen(ws_reg_wen),
        .ws_csr_wen(ws_csr_wen),
        .ws_csr_waddr1(ws_csr_waddr1),
        .ws_csr_waddr2(ws_csr_waddr2),
        .es_result_bypassable(es_result_bypassable),
        .ms_alu_fwd_valid(ms_alu_fwd_valid),
        .ms_load_bypass_valid(ms_load_bypass_valid),
        .ms_load_bypass_rd(ms_load_bypass_rd),
        .ws_alu_fwd_valid(ws_alu_fwd_valid),
        .ms_fwd_valid(ms_fwd_valid),
        .ms_fwd_data(ms_fwd_data),
        .ds_pc(ds_pc),
        .ds_instr(ds_instr),
        .ds_exc_valid(ds_exc_valid),
        .ds_exc_cause(ds_exc_cause),
        .ds_exc_tval(ds_exc_tval),
        .ds_rs1(ds_rs1),
        .ds_rs2(ds_rs2),
        .ds_src1(ds_src1),
        .ds_src2(ds_src2),
        .ds_src1_from_prev_ex(ds_src1_from_prev_ex),
        .ds_src2_from_prev_ex(ds_src2_from_prev_ex),
        .ds_src1_from_prev_wb(ds_src1_from_prev_wb),
        .ds_src2_from_prev_wb(ds_src2_from_prev_wb),
        .ds_pred_taken(ds_pred_taken),
        .ds_pred_target(ds_pred_target),
        .ds_pred_btb_hit(ds_pred_btb_hit),
        .ds_pred_btb_is_cond(ds_pred_btb_is_cond),
        .ds_pred_bht_state(ds_pred_bht_state),
        .ds_pred_pht_idx(ds_pred_pht_idx),
        .ds_imm(ds_imm),
        .ds_zimm(ds_zimm),
        .ds_scsr(ds_scsr),
        .ds_rd(ds_rd),
        .ds_reg_wen(ds_reg_wen),
        .ds_branch(ds_branch),
        .ds_datatoreg(ds_datatoreg),
        .ds_mem_wr(ds_mem_wr),
        .ds_mem_op(ds_mem_op),
        .ds_atomic_en(ds_atomic_en),
        .ds_atomic_op(ds_atomic_op),
        .ds_alu_a_src(ds_alu_a_src),
        .ds_alu_b_src(ds_alu_b_src),
        .ds_alu_ctr(ds_alu_ctr),
        .ds_csr_wen(ds_csr_wen),
        .ds_csr_waddr1(ds_csr_waddr1),
        .ds_csr_waddr2(ds_csr_waddr2),
        .ds_csr_wdata_src1(ds_csr_wdata_src1),
        .ds_csr_wdata_src2(ds_csr_wdata_src2),
        .ds_illegal(ds_illegal),
        .ds_is_ebreak(ds_is_ebreak),
        .ds_stop_fetch(ds_stop_fetch),
`ifdef NPC_USE_DPI
`ifdef NPC_PIPE_STAT
        .ds_stage_block(ds_stage_block),
        .ds_stage_block_reg_hazard(ds_stage_block_reg_hazard),
        .ds_stage_block_csr_hazard(ds_stage_block_csr_hazard),
        .ds_stage_block_load_use(ds_stage_block_load_use),
        .ds_stage_block_ex_raw(ds_stage_block_ex_raw),
        .ds_stage_block_ms_raw(ds_stage_block_ms_raw),
        .ds_stage_block_hidden_raw(ds_stage_block_hidden_raw),
        .ds_stat_uses_rs1(ds_stat_uses_rs1),
        .ds_stat_uses_rs2(ds_stat_uses_rs2),
        .ds_stat_rs1_match_es(ds_stat_rs1_match_es),
        .ds_stat_rs1_match_ms(ds_stat_rs1_match_ms),
        .ds_stat_rs1_match_hidden(ds_stat_rs1_match_hidden),
        .ds_stat_rs1_match_ws(ds_stat_rs1_match_ws),
        .ds_stat_rs2_match_es(ds_stat_rs2_match_es),
        .ds_stat_rs2_match_ms(ds_stat_rs2_match_ms),
        .ds_stat_rs2_match_hidden(ds_stat_rs2_match_hidden),
        .ds_stat_rs2_match_ws(ds_stat_rs2_match_ws),
        .ds_stat_csr_counter_hazard(ds_stat_csr_counter_hazard),
        .ds_stat_rs1_ex_alu_fwd(ds_stat_rs1_ex_alu_fwd),
        .ds_stat_rs2_ex_alu_fwd(ds_stat_rs2_ex_alu_fwd),
        .ds_stat_fwd_load_block(ds_stat_fwd_load_block),
        .ds_stat_fwd_csr_block(ds_stat_fwd_csr_block),
        .ds_stat_fwd_kill_block(ds_stat_fwd_kill_block),
`endif
`endif
`ifdef NPC_M_EXTENSION
        .ds_mdu_en(ds_mdu_en),
        .ds_mdu_op(ds_mdu_op)
`else
        .ds_mdu_en_dummy(ds_mdu_en_dummy),
        .ds_mdu_op_dummy(ds_mdu_op_dummy)
`endif
    );
    ex_stage u_ex_stage(
        .clk(clk),
        .rst_n(rst_n),
        .flush(flush_ex),
        .ds_to_es_valid(ds_to_es_fire),
        .es_allowin(es_allowin),
        .ms_allowin(ms_allowin),
        .es_to_ms_valid(es_to_ms_valid),
        .ds_pc(ds_pc),
        .ds_instr(ds_instr),
        .ds_exc_valid(ds_exc_valid),
        .ds_exc_cause(ds_exc_cause),
        .ds_exc_tval(ds_exc_tval),
        .ds_rs1(ds_rs1),
        .ds_rs2(ds_rs2),
        .ds_src1(ds_src1),
        .ds_src2(ds_src2),
        .ds_src1_from_prev_ex(ds_src1_from_prev_ex),
        .ds_src2_from_prev_ex(ds_src2_from_prev_ex),
        .ds_src1_from_prev_wb(ds_src1_from_prev_wb),
        .ds_src2_from_prev_wb(ds_src2_from_prev_wb),
        .ds_pred_taken(ds_pred_taken),
        .ds_pred_target(ds_pred_target),
        .ds_pred_btb_hit(ds_pred_btb_hit),
        .ds_pred_btb_is_cond(ds_pred_btb_is_cond),
        .ds_pred_bht_state(ds_pred_bht_state),
        .ds_pred_pht_idx(ds_pred_pht_idx),
        .ws_rf_wdata(ws_rf_wdata),
        .ms_alu_fwd_valid(ms_alu_fwd_valid),
        .ms_alu_fwd_rd(ms_rd),
        .ms_alu_fwd_data(ms_aluout),
        .ms_fast_mul_stat(ms_fast_mul_stat),
        .ms_load_bypass_valid(ms_load_bypass_valid),
        .ms_load_bypass_rd(ms_load_bypass_rd),
        .ms_load_bypass_data(ms_load_bypass_data),
        .hidden_alu_fwd_valid(hidden_alu_fwd_valid),
        .hidden_alu_fwd_rd(hidden_mreq_rd),
        .hidden_alu_fwd_data(hidden_mreq_aluout),
        .hidden_alu_fwd_fast_mul_stat(hidden_mreq_fast_mul_stat),
        .ws_alu_fwd_valid(ws_alu_fwd_valid),
        .ws_alu_fwd_rd(ws_rd),
        .ws_alu_fwd_data(ws_rf_wdata),
        .ws_load_fwd_valid(ws_load_fwd_valid),
        .ws_load_fwd_rd(ws_rd),
        .ws_load_fwd_data(ws_rf_wdata),
        .ws_fast_mul_stat(ws_fast_mul_stat),
        .ds_imm(ds_imm),
        .ds_zimm(ds_zimm),
        .ds_scsr(ds_scsr),
        .ds_rd(ds_rd),
        .ds_reg_wen(ds_reg_wen),
        .ds_branch(ds_branch),
        .ds_datatoreg(ds_datatoreg),
        .ds_mem_wr(ds_mem_wr),
        .ds_mem_op(ds_mem_op),
        .ds_atomic_en(ds_atomic_en),
        .ds_atomic_op(ds_atomic_op),
        .ds_alu_a_src(ds_alu_a_src),
        .ds_alu_b_src(ds_alu_b_src),
        .ds_alu_ctr(ds_alu_ctr),
        .ds_csr_wen(ds_csr_wen),
        .ds_csr_waddr1(ds_csr_waddr1),
        .ds_csr_waddr2(ds_csr_waddr2),
        .ds_csr_wdata_src1(ds_csr_wdata_src1),
        .ds_csr_wdata_src2(ds_csr_wdata_src2),
        .ds_illegal(ds_illegal),
        .ds_is_ebreak(ds_is_ebreak),
`ifdef NPC_M_EXTENSION
        .ds_mdu_en(ds_mdu_en),
        .ds_mdu_op(ds_mdu_op),
`endif
        .es_valid(es_valid),
        .es_result_bypassable(es_result_bypassable),
        .es_pc(es_pc),
        .es_instr(es_instr),
        .es_nextpc(es_nextpc),
        .es_rd(es_rd),
        .es_reg_wen(es_reg_wen),
        .es_datatoreg(es_datatoreg),
        .es_mem_wr(es_mem_wr),
        .es_mem_op(es_mem_op),
        .es_atomic_en(es_atomic_en),
        .es_atomic_op(es_atomic_op),
        .es_aluout(es_aluout),
        .es_mem_wdata(es_mem_wdata),
        .es_csr_read_data(es_csr_read_data),
        .es_csr_wen(es_csr_wen),
        .es_csr_waddr1(es_csr_waddr1),
        .es_csr_waddr2(es_csr_waddr2),
        .es_csr_wdata1(es_csr_wdata1),
        .es_csr_wdata2(es_csr_wdata2),
        .es_illegal(es_illegal),
        .es_exc_valid(es_exc_valid),
        .es_exc_cause(es_exc_cause),
        .es_exc_tval(es_exc_tval),
        .es_is_ebreak(es_is_ebreak),
        .es_branch(es_branch),
        .es_src1_value(es_src1_value),
        .es_mem_fwd_dep(es_mem_fwd_dep),
        .atomic_alu_ready(atomic_alu_ready),
        .atomic_alu_req_valid(atomic_alu_req_valid),
        .atomic_alu_op(atomic_alu_op),
        .atomic_alu_old(atomic_alu_old),
        .atomic_alu_rs2(atomic_alu_rs2),
        .atomic_alu_resp_valid(atomic_alu_resp_valid),
        .atomic_alu_result(atomic_alu_result),
`ifdef NPC_USE_DPI
`ifdef NPC_PIPE_STAT
        .es_stage_block(es_stage_block),
        .es_stage_block_mdu_wait(es_stage_block_mdu_wait),
        .es_stage_block_redirect_wait(es_stage_block_redirect_wait),
        .es_stat_is_mdu(es_stat_is_mdu),
        .es_stat_rs1_mem_alu_fwd(es_stat_rs1_mem_alu_fwd),
        .es_stat_rs2_mem_alu_fwd(es_stat_rs2_mem_alu_fwd),
        .es_stat_rs1_wb_fwd(es_stat_rs1_wb_fwd),
        .es_stat_rs2_wb_fwd(es_stat_rs2_wb_fwd),
        .es_stat_rs1_load_fwd(es_stat_rs1_load_fwd),
        .es_stat_rs2_load_fwd(es_stat_rs2_load_fwd),
        .es_stat_mdu_op(es_stat_mdu_op),
        .es_stat_mdu_req_fire(es_stat_mdu_req_fire),
        .es_stat_mdu_resp_valid(es_stat_mdu_resp_valid),
        .es_stat_mdu_busy(es_stat_mdu_busy),
        .es_stat_mdu_result_ready(es_stat_mdu_result_ready),
        .es_stat_fast_mul(es_stat_fast_mul),
        .es_stat_fast_mul_issue(es_stat_fast_mul_issue),
        .es_stat_fast_mul_resp(es_stat_fast_mul_resp_unused),
        .es_stat_fast_mul_kill(es_stat_fast_mul_kill),
        .es_stat_fast_mul_flush_drop(es_stat_fast_mul_flush_drop),
        .es_stat_fast_mul_forward(es_stat_fast_mul_forward),
        .es_stat_fast_mul_stall_wait_ready(es_stat_fast_mul_stall_wait_ready),
        .es_stat_old_div_path(es_stat_old_div_path),
        .es_stat_old_rem_path(es_stat_old_rem_path),
`endif
`endif
        .flush_valid(ex_flush_valid),
        .flush_pc(ex_flush_pc),
        .mispredict_flush_valid(ex_mispredict_flush_valid),
        .mispredict_flush_pc(ex_mispredict_flush_pc),
        .branch_taken_actual(ex_branch_taken_actual),
        .branch_pred_taken(ex_branch_pred_taken),
        .branch_pred_target(ex_branch_pred_target),
        .branch_pred_btb_hit(ex_branch_pred_btb_hit),
        .branch_pred_btb_is_cond(ex_branch_pred_btb_is_cond),
        .branch_pred_bht_state(ex_branch_pred_bht_state),
        .branch_pred_pht_idx(ex_branch_pred_pht_idx),
        .branch_target_mismatch(ex_branch_target_mismatch)
    );
    mem_stage u_mem_stage(
        .clk(clk),
        .rst_n(rst_n),
        .flush(flush_mem),
        .es_to_ms_valid(es_to_ms_valid),
        .ms_allowin(ms_allowin),
        .ws_allowin(ws_allowin),
        .ms_to_ws_valid(ms_to_ws_valid),
        .es_pc(es_pc),
        .es_instr(es_instr),
        .es_nextpc(es_nextpc),
        .es_rd(es_rd),
        .es_reg_wen(es_reg_wen),
        .es_datatoreg(es_datatoreg),
        .es_mem_wr(es_mem_wr),
        .es_mem_op(es_mem_op),
        .es_atomic_en(es_atomic_en),
        .es_atomic_op(es_atomic_op),
        .es_aluout(es_aluout),
        .es_mem_wdata(es_mem_wdata),
        .es_mem_fwd_dep(es_mem_fwd_dep),
        .es_fast_mul_stat(es_fast_mul_stat_to_mem),
        .es_csr_read_data(es_csr_read_data),
        .es_csr_wen(es_csr_wen),
        .es_csr_waddr1(es_csr_waddr1),
        .es_csr_waddr2(es_csr_waddr2),
        .es_csr_wdata1(es_csr_wdata1),
        .es_csr_wdata2(es_csr_wdata2),
        .es_illegal(es_illegal),
        .es_exc_valid(es_exc_valid),
        .es_exc_cause(es_exc_cause),
        .es_exc_tval(es_exc_tval),
        .es_is_ebreak(es_is_ebreak),
        .es_branch(es_branch),
        .es_src1_value(es_src1_value),
        .ms_valid(ms_valid),
        .ms_pc(ms_pc),
        .ms_instr(ms_instr),
        .ms_nextpc(ms_nextpc),
        .ms_rd(ms_rd),
        .ms_reg_wen(ms_reg_wen),
        .ms_datatoreg(ms_datatoreg),
        .ms_mem_op(ms_mem_op),
        .ms_aluout(ms_aluout),
        .ms_mem_rdata(ms_mem_rdata),
        .ms_csr_read_data(ms_csr_read_data),
        .ms_csr_wen(ms_csr_wen),
        .ms_csr_waddr1(ms_csr_waddr1),
        .ms_csr_waddr2(ms_csr_waddr2),
        .ms_csr_wdata1(ms_csr_wdata1),
        .ms_csr_wdata2(ms_csr_wdata2),
        .ms_illegal(ms_illegal),
        .ms_exc_valid(ms_exc_valid),
        .ms_exc_cause(ms_exc_cause),
        .ms_exc_tval(ms_exc_tval),
        .ms_is_ebreak(ms_is_ebreak),
        .ms_branch(ms_branch),
        .ms_src1_value(ms_src1_value),
        .ms_fast_mul_stat(ms_fast_mul_stat),
`ifdef NPC_USE_DPI
`ifdef NPC_PIPE_STAT
        .ms_stage_block(ms_stage_block),
        .ms_stage_block_req_phase(ms_stage_block_req_phase),
        .ms_stage_block_resp_phase(ms_stage_block_resp_phase),
        .ms_stage_block_load(ms_stage_block_load),
        .ms_stage_block_store(ms_stage_block_store),
        .ms_stage_block_req_load(ms_stage_block_req_load),
        .ms_stage_block_req_store(ms_stage_block_req_store),
        .ms_stage_block_resp_load(ms_stage_block_resp_load),
        .ms_stage_block_resp_store(ms_stage_block_resp_store),
        .fast_req_fire_trace(ms_fast_req_fire_trace),
        .slow_req_fire_trace(ms_slow_req_fire_trace),
        .slow_req_fwd_dep_fire_trace(ms_slow_req_fwd_dep_fire_trace),
        .slow_req_nonfwd_fire_trace(ms_slow_req_nonfwd_fire_trace),
        .ms_stat_load_visible(ms_stat_load_visible),
        .ms_stat_load_aligned(ms_stat_load_aligned),
        .ms_stat_load_result_ready(ms_stat_load_result_ready),
        .ms_stat_load_fault(ms_stat_load_fault),
        .ms_stat_load_signext_ready(ms_stat_load_signext_ready),
        .ms_stat_load_req_fire(ms_stat_load_req_fire),
        .ms_stat_load_resp_valid(ms_stat_load_resp_valid),
        .ms_stat_load_resp_fire(ms_stat_load_resp_fire),
        .ms_stat_load_data_ready(ms_stat_load_data_ready),
        .ms_stat_load_signext_data_ready(ms_stat_load_signext_data_ready),
        .ms_stat_load_to_wb_valid(ms_stat_load_to_wb_valid),
        .ms_stat_load_split_or_misaligned(ms_stat_load_split_or_misaligned),
        .ms_stat_load_uncached(ms_stat_load_uncached),
        .ms_stat_load_atomic(ms_stat_load_atomic),
        .ms_stat_load_killed(ms_stat_load_killed),
        .ms_stat_hidden_load(ms_stat_hidden_load),
        .ms_stat_load_store_block(ms_stat_load_store_block),
        .ms_stat_load_lsu_pending(ms_stat_load_lsu_pending),
        .ms_stat_mreq_valid(ms_stat_mreq_valid),
        .ms_stat_mreq_is_load(ms_stat_mreq_is_load),
        .ms_stat_mreq_is_store(ms_stat_mreq_is_store),
        .ms_stat_mreq_is_atomic(ms_stat_mreq_is_atomic),
        .ms_stat_mreq_need_mem(ms_stat_mreq_need_mem),
        .ms_stat_mreq_fire(ms_stat_mreq_fire),
        .ms_stat_mreq_misaligned(ms_stat_mreq_misaligned),
        .ms_stat_mreq_split(ms_stat_mreq_split),
        .ms_stat_mreq_fault(ms_stat_mreq_fault),
        .ms_stat_mreq_blocked_by_resp(ms_stat_mreq_blocked_by_resp),
        .ms_stat_mresp_valid(ms_stat_mresp_valid),
        .ms_stat_mresp_is_load(ms_stat_mresp_is_load),
        .ms_stat_mresp_is_store(ms_stat_mresp_is_store),
        .ms_stat_mresp_is_atomic(ms_stat_mresp_is_atomic),
        .ms_stat_mresp_resp_valid(ms_stat_mresp_resp_valid),
        .ms_stat_mresp_resp_fire(ms_stat_mresp_resp_fire),
        .ms_stat_mresp_split(ms_stat_mresp_split),
        .ms_stat_mresp_fault(ms_stat_mresp_fault),
        .ms_stat_store_visible(ms_stat_store_visible),
        .ms_stat_store_req_fire(ms_stat_store_req_fire),
        .ms_stat_store_resp_valid(ms_stat_store_resp_valid),
        .ms_stat_store_resp_fire(ms_stat_store_resp_fire),
        .ms_stat_store_aligned(ms_stat_store_aligned),
        .ms_stat_store_fault(ms_stat_store_fault),
        .ms_stat_store_split_or_misaligned(ms_stat_store_split_or_misaligned),
        .ms_stat_store_uncached(ms_stat_store_uncached),
        .ms_stat_store_atomic(ms_stat_store_atomic),
        .ms_stat_store_killed(ms_stat_store_killed),
        .ms_stat_store_buffer_safe(ms_stat_store_buffer_safe),
        .ms_stat_store_resp_wait(ms_stat_store_resp_wait),
        .ms_stat_single_outstanding_wait(ms_stat_single_outstanding_wait),
        .ms_stat_uncached_wait(ms_stat_uncached_wait),
        .ms_stat_writeback_wait(ms_stat_writeback_wait),
        .stat_exmem_skid_candidate(stat_exmem_skid_candidate),
        .stat_exmem_skid_enqueue(stat_exmem_skid_enqueue),
        .stat_exmem_skid_dequeue(stat_exmem_skid_dequeue),
        .stat_exmem_skid_full_stall(stat_exmem_skid_full_stall),
        .stat_exmem_skid_flush_drop(stat_exmem_skid_flush_drop),
        .stat_exmem_skid_blocked_not_safe(stat_exmem_skid_blocked_not_safe),
        .stat_exmem_skid_blocked_branch(stat_exmem_skid_blocked_branch),
        .stat_exmem_skid_blocked_mem(stat_exmem_skid_blocked_mem),
        .stat_exmem_skid_blocked_csr(stat_exmem_skid_blocked_csr),
        .stat_exmem_skid_blocked_exception(stat_exmem_skid_blocked_exception),
        .stat_exmem_skid_blocked_div(stat_exmem_skid_blocked_div),
        .stat_exmem_skid_blocked_structural(stat_exmem_skid_blocked_structural),
        .stat_exmem_skid_hold_cycles(stat_exmem_skid_hold_cycles),
        .stat_exmem_skid_hold_mem_wait_cycles(stat_exmem_skid_hold_mem_wait_cycles),
        .stat_exmem_skid_dequeue_after_mem_release(stat_exmem_skid_dequeue_after_mem_release),
        .stat_exmem_skid_dequeue_same_cycle_mem_release(stat_exmem_skid_dequeue_same_cycle_mem_release),
        .stat_exmem_skid_dequeue_causes_wb_valid(stat_exmem_skid_dequeue_causes_wb_valid),
        .stat_exmem_skid_valid(stat_exmem_skid_valid),
        .stat_exmem_skid_enqueue_fire(stat_exmem_skid_enqueue_fire),
        .stat_exmem_skid_dequeue_fire(stat_exmem_skid_dequeue_fire),
        .stat_exmem_skid_dequeue_commit_fire(stat_exmem_skid_dequeue_commit_fire),
        .stat_exmem_skid_dequeue_to_mreq_fire(stat_exmem_skid_dequeue_to_mreq_fire),
        .stat_exmem_skid_mem_wait(stat_exmem_skid_mem_wait),
        .stat_exmem_skid_mem_release(stat_exmem_skid_mem_release),
`endif
`endif
        .hidden_mreq_valid(hidden_mreq_valid),
        .hidden_mreq_reg_wen(hidden_mreq_reg_wen),
        .hidden_mreq_rd(hidden_mreq_rd),
        .hidden_mreq_datatoreg(hidden_mreq_datatoreg),
        .hidden_mreq_mem_wr(hidden_mreq_mem_wr),
        .hidden_mreq_aluout(hidden_mreq_aluout),
        .hidden_mreq_csr_wen(hidden_mreq_csr_wen),
        .hidden_mreq_csr_waddr1(hidden_mreq_csr_waddr1),
        .hidden_mreq_csr_waddr2(hidden_mreq_csr_waddr2),
        .hidden_mreq_fast_mul_stat(hidden_mreq_fast_mul_stat),
        .dbus_req_valid(dbus_req_valid),
        .dbus_req_ready(dbus_req_ready),
        .dbus_req_fast_ok(dbus_req_fast_ok),
        .dbus_req_fast_block_atomic(dbus_req_fast_block_atomic),
        .dbus_req_fast_block_misaligned(dbus_req_fast_block_misaligned),
        .dbus_req_fast_block_exception(dbus_req_fast_block_exception),
        .dbus_req_fast_block_phase2(dbus_req_fast_block_phase2),
        .dbus_req_fast_block_other(dbus_req_fast_block_other),
        .dbus_req_write(dbus_req_write),
        .dbus_req_atomic(dbus_req_atomic),
        .dbus_req_store_bufferable(dbus_req_store_bufferable),
        .dbus_req_addr(dbus_req_addr),
        .dbus_req_wdata(dbus_req_wdata),
        .dbus_req_wstrb(dbus_req_wstrb),
        .dbus_req_len(dbus_req_len),
        .dbus_resp_valid(dbus_resp_valid),
        .dbus_resp_ready(dbus_resp_ready),
        .dbus_resp_data(dbus_resp_data),
        .dbus_resp_exc_valid(dbus_resp_exc_valid),
        .dbus_resp_exc_cause(dbus_resp_exc_cause),
        .dbus_resp_exc_tval(dbus_resp_exc_tval),
        .atomic_alu_ready(atomic_alu_ready),
        .atomic_alu_req_valid(atomic_alu_req_valid),
        .atomic_alu_op(atomic_alu_op),
        .atomic_alu_old(atomic_alu_old),
        .atomic_alu_rs2(atomic_alu_rs2),
        .atomic_alu_resp_valid(atomic_alu_resp_valid),
        .atomic_alu_result(atomic_alu_result),
        .dbg_mreq_valid(dbg_mem_mreq_valid),
        .dbg_mresp_valid(dbg_mem_mresp_valid),
        .dbg_skid_valid(dbg_mem_skid_valid),
        .dbg_mreq_instr(dbg_mem_mreq_instr),
        .dbg_mresp_instr(dbg_mem_mresp_instr),
        .dbg_mreq_need_mem(dbg_mem_mreq_need_mem),
        .dbg_mreq_req_valid(dbg_mem_mreq_req_valid),
        .dbg_mreq_mem_fire(dbg_mem_mreq_mem_fire),
        .dbg_mreq_nonmem_fire(dbg_mem_mreq_nonmem_fire),
        .dbg_mreq_consumed_eff(dbg_mem_mreq_consumed_eff),
        .dbg_mresp_ready_go(dbg_mem_mresp_ready_go),
        .dbg_mresp_commit_fire(dbg_mem_mresp_commit_fire),
        .dbg_old_mreq_allowin(dbg_mem_old_mreq_allowin),
        .dbg_mresp_atomic_en(dbg_mem_mresp_atomic_en),
        .dbg_mresp_split(dbg_mem_mresp_split),
        .dbg_mresp_phase1_amo_read(dbg_mem_mresp_phase1_amo_read)
    );
    wb_stage u_wb_stage(
        .clk(clk),
        .rst_n(rst_n),
        .flush(wb_flush),
        .hold(store_buffer_drain_before_maint),
        .ms_to_ws_valid(ms_to_ws_valid),
        .ws_allowin(ws_allowin),
        .ms_pc(ms_pc),
        .ms_instr(ms_instr),
        .ms_nextpc(ms_nextpc),
        .ms_rd(ms_rd),
        .ms_reg_wen(ms_reg_wen),
        .ms_datatoreg(ms_datatoreg),
        .ms_mem_op(ms_mem_op),
        .ms_aluout(ms_aluout),
        .ms_mem_rdata(ms_mem_rdata),
        .ms_csr_read_data(ms_csr_read_data),
        .ms_csr_wen(ms_csr_wen),
        .ms_csr_waddr1(ms_csr_waddr1),
        .ms_csr_waddr2(ms_csr_waddr2),
        .ms_csr_wdata1(ms_csr_wdata1),
        .ms_csr_wdata2(ms_csr_wdata2),
        .ms_illegal(ms_illegal),
        .ms_exc_valid(ms_exc_valid),
        .ms_exc_cause(ms_exc_cause),
        .ms_exc_tval(ms_exc_tval),
        .ms_is_ebreak(ms_is_ebreak),
        .ms_branch(ms_branch),
        .ms_src1_value(ms_src1_value),
        .ms_fast_mul_stat(ms_fast_mul_stat),
        .ws_valid(ws_valid),
        .ws_pc(ws_pc),
        .ws_instr(ws_instr),
        .ws_nextpc(ws_nextpc),
        .ws_rd(ws_rd),
        .ws_reg_wen(ws_reg_wen),
        .ws_rf_wdata(ws_rf_wdata),
        .ws_stat_datatoreg(ws_stat_datatoreg),
        .ws_stat_mem_op(ws_stat_mem_op),
        .ws_csr_wen(ws_csr_wen),
        .ws_csr_waddr1(ws_csr_waddr1),
        .ws_csr_waddr2(ws_csr_waddr2),
        .ws_csr_wdata1(ws_csr_wdata1),
        .ws_csr_wdata2(ws_csr_wdata2),
        .ws_illegal(ws_illegal),
        .ws_exc_valid(ws_exc_valid),
        .ws_exc_cause(ws_exc_cause),
        .ws_exc_tval(ws_exc_tval),
        .ws_is_ebreak(ws_is_ebreak),
        .ws_branch(ws_branch),
        .ws_src1_value(ws_src1_value),
        .ws_fast_mul_stat(ws_fast_mul_stat)
    );

endmodule
