`timescale 1ns / 1ps

module CpuPerfMonitors #(
    parameter integer ICACHE_MISS_PENALTY = 20,
    parameter integer DCACHE_MISS_PENALTY = 20
) (
    input clk,
    input rst_n,
    input ws_valid,
    input commit_is_ebreak,
    input ws_illegal,
    input [31:0] ws_pc,
    input [31:0] ws_instr,
    input [31:0] ws_nextpc,
    input ibus_req_valid_w,
    input ibus_req_ready,
    input ibus_resp_valid,
    input ibus_resp_ready_w,
    input dbus_req_valid,
    input dbus_req_ready,
    input dbus_resp_valid,
    input dbus_resp_ready,
    input [63:0] icache_stat_access,
    input [63:0] icache_stat_hit,
    input [63:0] icache_stat_miss,
    input [63:0] icache_stat_refill_req,
    input [63:0] icache_stat_refill_resp,
    input [63:0] icache_stat_refill_bypass,
    input [63:0] icache_stat_req_wait_cycle,
    input [63:0] icache_stat_hit_resp_wait_cycle,
    input [63:0] icache_stat_miss_wait_cycle,
    input [63:0] icache_stat_uncached_access,
    input [63:0] icache_pipe_req_valid_cycle,
    input [63:0] icache_pipe_req_ready_cycle,
    input [63:0] icache_pipe_req_fire_cycle,
    input [63:0] icache_pipe_req_valid_not_ready_cycle,
    input [63:0] icache_pipe_resp_valid_cycle,
    input [63:0] icache_pipe_resp_ready_cycle,
    input [63:0] icache_pipe_resp_fire_cycle,
    input [63:0] icache_pipe_data_valid_cycle,
    input [63:0] icache_pipe_resp_block_cycle,
    input [63:0] icache_pipe_ready_block_state_cycle,
    input [63:0] icache_pipe_ready_block_data_cycle,
    input [63:0] icache_pipe_ready_block_resp_cycle,
    input [63:0] icache_pipe_ready_block_cpu_cycle,
    input [63:0] icache_pipe_ready_block_maint_cycle,
    input [63:0] icache_pipe_state_idle_cycle,
    input [63:0] icache_pipe_state_refill_cycle,
    input [63:0] icache_pipe_state_uncached_cycle,
    input [63:0] icache_pipe_hit_fire_cycle,
    input [63:0] icache_pipe_miss_fire_cycle,
    input [63:0] icache_pipe_refill_busy_cycle,
    input [63:0] icache_pipe_resp_fifo_full_cycle,
    input [63:0] dcache_stat_access,
    input [63:0] dcache_stat_load_access,
    input [63:0] dcache_stat_store_access,
    input [63:0] dcache_stat_load_hit,
    input [63:0] dcache_stat_load_miss,
    input [63:0] dcache_stat_store_hit,
    input [63:0] dcache_stat_store_miss,
    input [63:0] dcache_stat_refill_req,
    input [63:0] dcache_stat_refill_resp,
    input [63:0] dcache_stat_write_req,
    input [63:0] dcache_stat_write_resp,
    input [63:0] dcache_stat_refill_ld_bypass,
    input [63:0] dcache_stat_refill_store_merge,
    input [63:0] dcache_stat_req_wait_cycle,
    input [63:0] dcache_stat_hit_resp_wait_cycle,
    input [63:0] dcache_stat_miss_wait_cycle,
    input [63:0] dcache_stat_uncached_access,
    input [63:0] dcache_stat_writeback_cycle,
    input [63:0] dhitopt_candidate_count,
    input [63:0] dhitopt_success_count,
    input [63:0] dhitopt_fallback_count,
    input [63:0] dhitopt_block_store_buffer_count,
    input [63:0] dhitopt_block_uncached_count,
    input [63:0] dhitopt_block_fault_count,
    input [63:0] dhitopt_block_miss_count,
    input [63:0] dhitopt_block_alignment_count,
    input [63:0] dhitopt_unknown_count,
    input fs_to_ds_valid,
    input if_stall,
    input ds_allowin,
    input ds_to_es_valid,
    input [31:0] ds_pc,
    input [31:0] ds_instr,
    input ds_stage_block,
    input ds_stage_block_reg_hazard,
    input ds_stage_block_csr_hazard,
    input ds_stage_block_load_use,
    input ds_stage_block_ex_raw,
    input ds_stage_block_ms_raw,
    input ds_stage_block_hidden_raw,
    input ds_stat_uses_rs1,
    input ds_stat_uses_rs2,
    input ds_stat_rs1_match_es,
    input ds_stat_rs1_match_ms,
    input ds_stat_rs1_match_hidden,
    input ds_stat_rs1_match_ws,
    input ds_stat_rs2_match_es,
    input ds_stat_rs2_match_ms,
    input ds_stat_rs2_match_hidden,
    input ds_stat_rs2_match_ws,
    input ds_stat_csr_counter_hazard,
    input ds_stat_rs1_ex_alu_fwd,
    input ds_stat_rs2_ex_alu_fwd,
    input ds_stat_fwd_load_block,
    input ds_stat_fwd_csr_block,
    input ds_stat_fwd_kill_block,
    input es_allowin,
    input es_to_ms_valid,
    input es_valid,
    input es_result_bypassable,
    input [31:0] es_pc,
    input [31:0] es_instr,
    input [31:0] es_nextpc,
    input [1:0] es_datatoreg,
    input [1:0] es_mem_wr,
    input es_atomic_en,
    input [1:0] es_csr_wen,
    input [2:0] es_branch,
    input es_mem_fwd_dep,
    input es_stage_block,
    input es_stage_block_mdu_wait,
    input es_stage_block_redirect_wait,
    input es_stat_is_mdu,
    input es_stat_rs1_mem_alu_fwd,
    input es_stat_rs2_mem_alu_fwd,
    input es_stat_rs1_wb_fwd,
    input es_stat_rs2_wb_fwd,
    input es_stat_rs1_load_fwd,
    input es_stat_rs2_load_fwd,
    input [2:0] es_stat_mdu_op,
    input es_stat_mdu_req_fire,
    input es_stat_mdu_resp_valid,
    input es_stat_mdu_busy,
    input es_stat_mdu_result_ready,
    input es_stat_fast_mul,
    input es_stat_fast_mul_issue,
    input fast_mul_resp_wb,
    input es_stat_fast_mul_kill,
    input es_stat_fast_mul_flush_drop,
    input es_stat_fast_mul_forward,
    input es_stat_fast_mul_stall_wait_ready,
    input es_stat_old_div_path,
    input es_stat_old_rem_path,
    input ex_mispredict_flush_valid,
    input ex_branch_taken_actual,
    input ex_branch_pred_taken,
    input [31:0] ex_branch_pred_target,
    input ex_branch_pred_btb_hit,
    input ex_branch_pred_btb_is_cond,
    input [1:0] ex_branch_pred_bht_state,
    input ex_branch_target_mismatch,
    input redirect_flush_valid,
    input vm_flush_start,
    input ms_allowin,
    input ms_to_ws_valid,
    input ms_valid,
    input [1:0] ms_datatoreg,
    input [1:0] ms_csr_wen,
    input ms_stage_block,
    input ms_stage_block_req_phase,
    input ms_stage_block_resp_phase,
    input ms_stage_block_load,
    input ms_stage_block_store,
    input ms_stage_block_req_load,
    input ms_stage_block_req_store,
    input ms_stage_block_resp_load,
    input ms_stage_block_resp_store,
    input ms_fast_req_fire_trace,
    input ms_slow_req_fire_trace,
    input ms_slow_req_fwd_dep_fire_trace,
    input ms_slow_req_nonfwd_fire_trace,
    input ms_stat_load_visible,
    input ms_stat_load_aligned,
    input ms_stat_load_result_ready,
    input ms_stat_load_fault,
    input ms_stat_load_signext_ready,
    input ms_stat_load_req_fire,
    input ms_stat_load_resp_valid,
    input ms_stat_load_resp_fire,
    input ms_stat_load_data_ready,
    input ms_stat_load_signext_data_ready,
    input ms_stat_load_to_wb_valid,
    input ms_stat_load_split_or_misaligned,
    input ms_stat_load_uncached,
    input ms_stat_load_atomic,
    input ms_stat_load_killed,
    input ms_stat_hidden_load,
    input ms_stat_load_store_block,
    input ms_stat_load_lsu_pending,
    input ms_stat_mreq_valid,
    input ms_stat_mreq_is_load,
    input ms_stat_mreq_is_store,
    input ms_stat_mreq_is_atomic,
    input ms_stat_mreq_need_mem,
    input ms_stat_mreq_fire,
    input ms_stat_mreq_misaligned,
    input ms_stat_mreq_split,
    input ms_stat_mreq_fault,
    input ms_stat_mreq_blocked_by_resp,
    input ms_stat_mresp_valid,
    input ms_stat_mresp_is_load,
    input ms_stat_mresp_is_store,
    input ms_stat_mresp_is_atomic,
    input ms_stat_mresp_resp_valid,
    input ms_stat_mresp_resp_fire,
    input ms_stat_mresp_split,
    input ms_stat_mresp_fault,
    input ms_stat_store_visible,
    input ms_stat_store_req_fire,
    input ms_stat_store_resp_valid,
    input ms_stat_store_resp_fire,
    input ms_stat_store_aligned,
    input ms_stat_store_fault,
    input ms_stat_store_split_or_misaligned,
    input ms_stat_store_uncached,
    input ms_stat_store_atomic,
    input ms_stat_store_killed,
    input ms_stat_store_buffer_safe,
    input ms_stat_store_resp_wait,
    input ms_stat_single_outstanding_wait,
    input ms_stat_uncached_wait,
    input ms_stat_writeback_wait,
    input [63:0] stat_exmem_skid_candidate,
    input [63:0] stat_exmem_skid_enqueue,
    input [63:0] stat_exmem_skid_dequeue,
    input [63:0] stat_exmem_skid_full_stall,
    input [63:0] stat_exmem_skid_flush_drop,
    input [63:0] stat_exmem_skid_blocked_not_safe,
    input [63:0] stat_exmem_skid_blocked_branch,
    input [63:0] stat_exmem_skid_blocked_mem,
    input [63:0] stat_exmem_skid_blocked_csr,
    input [63:0] stat_exmem_skid_blocked_exception,
    input [63:0] stat_exmem_skid_blocked_div,
    input [63:0] stat_exmem_skid_blocked_structural,
    input [63:0] stat_exmem_skid_hold_cycles,
    input [63:0] stat_exmem_skid_hold_mem_wait_cycles,
    input [63:0] stat_exmem_skid_dequeue_after_mem_release,
    input [63:0] stat_exmem_skid_dequeue_same_cycle_mem_release,
    input [63:0] stat_exmem_skid_dequeue_causes_wb_valid,
    input stat_exmem_skid_valid,
    input stat_exmem_skid_enqueue_fire,
    input stat_exmem_skid_dequeue_fire,
    input stat_exmem_skid_dequeue_commit_fire,
    input stat_exmem_skid_dequeue_to_mreq_fire,
    input stat_exmem_skid_mem_wait,
    input stat_exmem_skid_mem_release,
    input [63:0] store_buffer_enqueue_count,
    input [63:0] store_buffer_dequeue_count,
    input [63:0] store_buffer_full_stall_count,
    input [63:0] store_buffer_drain_req_count,
    input [63:0] store_buffer_drain_resp_count,
    input [63:0] store_buffer_drain_wait_count,
    input [63:0] store_buffer_load_forward_count,
    input [63:0] store_buffer_load_stall_conflict_count,
    input [63:0] store_buffer_load_stall_buffer_nonempty_count,
    input [63:0] store_buffer_fence_drain_wait_count,
    input [63:0] store_buffer_uncached_drain_wait_count,
    input [63:0] store_buffer_killed_store_block_count,
    input [63:0] store_buffer_occupancy0_count,
    input [63:0] store_buffer_occupancy1_count,
    input [63:0] store_buffer_occupancy2_count,
    input [63:0] store_buffer_max_occupancy_count,
    input [63:0] store_buffer_enqueue_occ0_count,
    input [63:0] store_buffer_enqueue_occ1_count,
    input [63:0] store_buffer_enqueue_full_count,
    input [1:0] hidden_mreq_datatoreg,
    input [1:0] hidden_mreq_mem_wr,
    input [1:0] hidden_mreq_csr_wen,
    input [1:0] ws_stat_datatoreg,
    input [2:0] ws_stat_mem_op,
    input [1:0] ws_csr_wen,
    input redirect_clear_valid,
    input stop_clear_valid,
    input trap_redirect_valid,
    input fencei_start,
    input fencei_maint_active,
    input [63:0] if_pipe_epoch_drop_count,
    input [63:0] if_pipe_stall_cycle,
    input [63:0] if_pipe_icache_miss_count,
    input if_stat_fs_valid,
    input [1:0] if_stat_queue_count,
    input if_stat_fetch_room,
    input if_stat_req_fire,
    input if_stat_resp_fire,
    input if_stat_resp_accept,
    input if_stat_resp_drop,
    input if_stat_bypass_direct,
    input if_stat_waiting_resp,
    input if_stat_drop_resp,
    input if_stat_fs_pop,
    input if_stat_resp_enq,
    input if_stat_queue_full,
    input if_stat_resp_block,
    input if_pipe_stat_outstanding,
    input if_pipe_stat_replay_valid,
    input if_pipe_stat_ptw_busy,
    input if_pipe_stat_req_valid,
    input if_pipe_stat_req_ready,
    input if_pipe_stat_resp_current,
    input if_pipe_stat_resp_stale,
    input if_pipe_stat_lower_req_valid,
    input if_pipe_stat_lower_req_ready,
    input if_pipe_stat_lower_resp_valid,
    input if_pipe_stat_lower_resp_ready,
    input ibus_icache_pipe_resp_valid,
    input ibus_icache_pipe_resp_ready,
    input ws_allowin,
    input ms_fwd_valid,
    input [63:0] if_mmu_req_count,
    input [63:0] if_mmu_bypass_count,
    input [63:0] if_mmu_translate_count,
    input [63:0] if_mmu_ptw_cycle_count,
    input [63:0] if_mmu_ptw_l1_read_count,
    input [63:0] if_mmu_ptw_l0_read_count,
    input [63:0] if_mmu_page_fault_count,
    input [63:0] if_mmu_ptw_walk_start_count,
    input [63:0] if_mmu_ptw_walk_done_count,
    input [63:0] if_mmu_ptw_walk_fault_count,
    input [63:0] if_mmu_tlb_hit_count,
    input [63:0] if_mmu_tlb_miss_count,
    input [63:0] if_mmu_tlb_hit_to_cache_req_cycle,
    input [63:0] if_mmu_cache_req_wait_cycle,
    input [63:0] if_mmu_cache_resp_wait_cycle,
    input [63:0] if_mmu_bridge_state_wait_cycle,
    input [63:0] if_mmu_fetch_req_count,
    input [63:0] if_mmu_fetch_resp_count,
    input [63:0] if_pipe_issue_count,
    input [63:0] if_pipe_resp_count,
    input [63:0] if_pipe_replay_count,
    input [63:0] if_pipe_ptw_miss_count,
    input [63:0] if_pipe_ptw_fault_count,
    input [63:0] if_pipe_icache_replay_count,
    input [63:0] lsu_mmu_req_count,
    input [63:0] lsu_mmu_bypass_count,
    input [63:0] lsu_mmu_translate_count,
    input [63:0] lsu_mmu_ptw_cycle_total,
    input [63:0] lsu_mmu_ptw_l1_read_total,
    input [63:0] lsu_mmu_ptw_l0_read_total,
    input [63:0] lsu_mmu_page_fault_count,
    input [63:0] lsu_mmu_ptw_walk_start_total,
    input [63:0] lsu_mmu_ptw_walk_done_total,
    input [63:0] lsu_mmu_ptw_walk_fault_total,
    input [63:0] lsu_mmu_tlb_hit_count,
    input [63:0] lsu_mmu_tlb_miss_count,
    input [63:0] lsu_mmu_tlb_hit_to_cache_req_cycle,
    input [63:0] lsu_mmu_cache_req_wait_cycle,
    input [63:0] lsu_mmu_cache_resp_wait_cycle,
    input [63:0] lsu_mmu_bridge_state_wait_cycle,
    input [63:0] lsu_mmu_data_req_count,
    input [63:0] lsu_mmu_data_resp_count,
    input [63:0] lsu_mmu_uncached_req_count,
    input [63:0] lsu_pipe_issue_count,
    input [63:0] lsu_pipe_resp_count,
    input [63:0] lsu_pipe_epoch_drop_count,
    input [63:0] lsu_pipe_dtlb_hit_count,
    input [63:0] lsu_pipe_dtlb_miss_count,
    input [63:0] lsu_pipe_replay_count,
    input [63:0] lsu_pipe_fault_count,
    input [63:0] lsu_pipe_stall_cycle,
    input [63:0] lsu_pipe_dcache_hit_count,
    input [63:0] lsu_pipe_dcache_miss_count,
    input [63:0] lsu_pipe_store_hit_count,
    input [63:0] lsu_pipe_load_hit_count,
    input [63:0] lsu_pipe_slow_fallback_count,
    input [63:0] lsu_pipe_load_miss_replay_count,
    input [63:0] lsu_pipe_store_miss_replay_count,
    input [63:0] lsu_pipe_direct_uncached_count,
    input [63:0] lsu_pipe_direct_non_dtlb_hit_count,
    input [63:0] lsu_pipe_direct_perm_fault_count,
    input [63:0] lsu_pipe_direct_cross_page_count,
    input [63:0] lsu_pipe_direct_fast_block_count,
    input [63:0] lsu_pipe_direct_fast_block_atomic_count,
    input [63:0] lsu_pipe_direct_fast_block_misaligned_count,
    input [63:0] lsu_pipe_direct_fast_block_exception_count,
    input [63:0] lsu_pipe_direct_fast_block_phase2_count,
    input [63:0] lsu_pipe_direct_fast_block_other_count,
    input [63:0] lsu_pipe_direct_other_count,
    input [63:0] lsu_pipe_hit_latency_sum,
    input [63:0] lsu_pipe_hit_latency_count,
    input [63:0] lsu_pipe_hit_latency_max,
    input [63:0] lsu_pipe_load_hit_latency_sum,
    input [63:0] lsu_pipe_load_hit_latency_count,
    input [63:0] lsu_pipe_load_hit_latency_max,
    input [63:0] lsu_pipe_store_hit_latency_sum,
    input [63:0] lsu_pipe_store_hit_latency_count,
    input [63:0] lsu_pipe_store_hit_latency_max,
    input [63:0] lsu_pipe_slow_fallback_latency_sum,
    input [63:0] lsu_pipe_slow_fallback_latency_count,
    input [63:0] lsu_pipe_slow_fallback_latency_max,
    input [63:0] lsu_pipe_slow_direct_latency_sum,
    input [63:0] lsu_pipe_slow_direct_latency_count,
    input [63:0] lsu_pipe_slow_direct_latency_max,
    input [63:0] lsu_pipe_slow_replay_latency_sum,
    input [63:0] lsu_pipe_slow_replay_latency_count,
    input [63:0] lsu_pipe_slow_replay_latency_max,
    input branch_stat_fetch_req_valid,
    input [31:0] branch_stat_fetch_req_pc,
    input branch_stat_fetch_accept_valid,
    input [31:0] branch_stat_fetch_accept_pc,
    input [31:0] branch_stat_fetch_accept_instr,
    input branch_stat_fetch_drop_valid,
    input branch_stat_fetch_drop_redirect,
    input [31:0] branch_stat_fetch_drop_pc,
    input [31:0] branch_stat_fetch_drop_instr,
    input branch_stat_resolve_valid,
    input [63:0] bpu_btb_lookup_count,
    input [63:0] bpu_btb_hit_count,
    input [63:0] bpu_btb_miss_count,
    input [63:0] bpu_bht_pred_taken_count,
    input [63:0] bpu_bht_pred_not_taken_count,
    input [63:0] bpu_btb_conflict_count,
    input [63:0] bpu_btb_update_count,
    input [63:0] bpu_btb_replace_count,
    input [63:0] bpu_bht_lookup_count,
    input [63:0] bpu_bht_update_count,
    input [63:0] bpu_bht_weak_taken_count,
    input [63:0] bpu_bht_weak_not_taken_count,
    input [63:0] bpu_bht_strong_taken_count,
    input [63:0] bpu_bht_strong_not_taken_count,
    input bpu_gshare_enable,
    input [31:0] bpu_bhr_bits,
    input [31:0] bpu_bhr_value
);
`ifdef NPC_BRANCH_STAT
    wire [63:0] branch_stat_redirect_wait_cycle;
    wire [63:0] branch_stat_redirect_count;
    wire [63:0] branch_stat_mispredict_count;
`else
    wire [63:0] branch_stat_redirect_wait_cycle = 64'd0;
    wire [63:0] branch_stat_redirect_count = 64'd0;
    wire [63:0] branch_stat_mispredict_count = 64'd0;
`endif

`ifdef NPC_PIPE_STAT
    wire [63:0] pipe_stat_load_use_stall_cycle;
    wire [63:0] pipe_stat_id_reg_hazard_cycle;
    wire [63:0] pipe_stat_ms_block_cycle;
`else
    wire [63:0] pipe_stat_load_use_stall_cycle = 64'd0;
    wire [63:0] pipe_stat_id_reg_hazard_cycle = 64'd0;
    wire [63:0] pipe_stat_ms_block_cycle = 64'd0;
`endif

`ifdef NPC_USE_DPI
`ifdef NPC_BRANCH_STAT
    BranchStat u_branch_stat(
        .clk(clk),
        .rst_n(rst_n),
        .fetch_req_valid(branch_stat_fetch_req_valid),
        .fetch_req_pc(branch_stat_fetch_req_pc),
        .fetch_accept_valid(branch_stat_fetch_accept_valid),
        .fetch_accept_pc(branch_stat_fetch_accept_pc),
        .fetch_accept_instr(branch_stat_fetch_accept_instr),
        .fetch_drop_valid(branch_stat_fetch_drop_valid),
        .fetch_drop_redirect(branch_stat_fetch_drop_redirect),
        .fetch_drop_pc(branch_stat_fetch_drop_pc),
        .fetch_drop_instr(branch_stat_fetch_drop_instr),
        .branch_resolve_valid(branch_stat_resolve_valid),
        .branch_kind(es_branch),
        .branch_pc(es_pc),
        .branch_instr(es_instr),
        .branch_nextpc(es_nextpc),
        .branch_redirect(ex_mispredict_flush_valid),
        .branch_taken(ex_branch_taken_actual),
        .branch_pred_taken(ex_branch_pred_taken),
        .branch_pred_target(ex_branch_pred_target),
        .branch_pred_btb_hit(ex_branch_pred_btb_hit),
        .branch_pred_btb_is_cond(ex_branch_pred_btb_is_cond),
        .branch_pred_bht_state(ex_branch_pred_bht_state),
        .branch_target_mismatch(ex_branch_target_mismatch),
        .bpu_btb_lookup_count(bpu_btb_lookup_count),
        .bpu_btb_hit_count(bpu_btb_hit_count),
        .bpu_btb_miss_count(bpu_btb_miss_count),
        .bpu_bht_pred_taken_count(bpu_bht_pred_taken_count),
        .bpu_bht_pred_not_taken_count(bpu_bht_pred_not_taken_count),
        .bpu_btb_conflict_count(bpu_btb_conflict_count),
        .bpu_btb_update_count(bpu_btb_update_count),
        .bpu_btb_replace_count(bpu_btb_replace_count),
        .bpu_bht_lookup_count(bpu_bht_lookup_count),
        .bpu_bht_update_count(bpu_bht_update_count),
        .bpu_bht_weak_taken_count(bpu_bht_weak_taken_count),
        .bpu_bht_weak_not_taken_count(bpu_bht_weak_not_taken_count),
        .bpu_bht_strong_taken_count(bpu_bht_strong_taken_count),
        .bpu_bht_strong_not_taken_count(bpu_bht_strong_not_taken_count),
        .bpu_gshare_enable(bpu_gshare_enable),
        .bpu_bhr_bits(bpu_bhr_bits),
        .bpu_bhr_value(bpu_bhr_value),
        .stop_clear_valid(stop_clear_valid),
        .stop_clear_pc(ds_pc),
        .stop_clear_instr(ds_instr),
        .commit_valid(ws_valid),
        .commit_pc(ws_pc),
        .commit_instr(ws_instr),
        .commit_nextpc(ws_nextpc),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal),
        .ibus_req_valid(ibus_req_valid_w),
        .ibus_req_ready(ibus_req_ready),
        .ibus_resp_valid(ibus_resp_valid),
        .ibus_resp_ready(ibus_resp_ready_w),
        .dbus_req_valid(dbus_req_valid),
        .dbus_req_ready(dbus_req_ready),
        .dbus_resp_valid(dbus_resp_valid),
        .dbus_resp_ready(dbus_resp_ready),
        .if_mmu_translate_count(if_mmu_translate_count),
        .lsu_mmu_translate_count(lsu_mmu_translate_count),
        .stat_redirect_wait_cycle(branch_stat_redirect_wait_cycle),
        .stat_redirect_count(branch_stat_redirect_count),
        .stat_mispredict_count(branch_stat_mispredict_count)
    );
`endif

`ifdef NPC_MMU_STAT
    MMUStat u_mmu_stat(
        .clk(clk),
        .rst_n(rst_n),
        .commit_valid(ws_valid),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal),
        .if_req_count(if_mmu_req_count),
        .if_bypass_count(if_mmu_bypass_count),
        .if_translate_count(if_mmu_translate_count),
        .if_ptw_cycle_count(if_mmu_ptw_cycle_count),
        .if_ptw_l1_read_count(if_mmu_ptw_l1_read_count),
        .if_ptw_l0_read_count(if_mmu_ptw_l0_read_count),
        .if_page_fault_count(if_mmu_page_fault_count),
        .if_ptw_walk_start_count(if_mmu_ptw_walk_start_count),
        .if_ptw_walk_done_count(if_mmu_ptw_walk_done_count),
        .if_ptw_walk_fault_count(if_mmu_ptw_walk_fault_count),
        .if_tlb_hit_count(if_mmu_tlb_hit_count),
        .if_tlb_miss_count(if_mmu_tlb_miss_count),
        .lsu_req_count(lsu_mmu_req_count),
        .lsu_bypass_count(lsu_mmu_bypass_count),
        .lsu_translate_count(lsu_mmu_translate_count),
        .lsu_ptw_cycle_count(lsu_mmu_ptw_cycle_total),
        .lsu_ptw_l1_read_count(lsu_mmu_ptw_l1_read_total),
        .lsu_ptw_l0_read_count(lsu_mmu_ptw_l0_read_total),
        .lsu_page_fault_count(lsu_mmu_page_fault_count),
        .lsu_ptw_walk_start_count(lsu_mmu_ptw_walk_start_total),
        .lsu_ptw_walk_done_count(lsu_mmu_ptw_walk_done_total),
        .lsu_ptw_walk_fault_count(lsu_mmu_ptw_walk_fault_total),
        .lsu_tlb_hit_count(lsu_mmu_tlb_hit_count),
        .lsu_tlb_miss_count(lsu_mmu_tlb_miss_count)
    );
`endif

`ifdef NPC_HIT_PATH_STAT
    HitPathStat u_hit_path_stat(
        .clk(clk),
        .rst_n(rst_n),
        .commit_valid(ws_valid),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal),
        .if_ptw_cycle(if_mmu_ptw_cycle_count),
        .lsu_ptw_cycle(lsu_mmu_ptw_cycle_total),
        .if_tlb_hit_to_cache_req_cycle(if_mmu_tlb_hit_to_cache_req_cycle),
        .lsu_tlb_hit_to_cache_req_cycle(lsu_mmu_tlb_hit_to_cache_req_cycle),
        .if_bridge_state_wait_cycle(if_mmu_bridge_state_wait_cycle),
        .lsu_bridge_state_wait_cycle(lsu_mmu_bridge_state_wait_cycle),
        .if_cache_req_wait_cycle(if_mmu_cache_req_wait_cycle),
        .if_cache_resp_wait_cycle(if_mmu_cache_resp_wait_cycle),
        .lsu_cache_req_wait_cycle(lsu_mmu_cache_req_wait_cycle),
        .lsu_cache_resp_wait_cycle(lsu_mmu_cache_resp_wait_cycle),
        .if_fetch_req_count(if_mmu_fetch_req_count),
        .if_fetch_resp_count(if_mmu_fetch_resp_count),
        .if_pipe_issue_count(if_pipe_issue_count),
        .if_pipe_resp_count(if_pipe_resp_count),
        .if_pipe_epoch_drop_count(if_pipe_epoch_drop_count),
        .if_pipe_replay_count(if_pipe_replay_count),
        .if_pipe_ptw_miss_count(if_pipe_ptw_miss_count),
        .if_pipe_ptw_fault_count(if_pipe_ptw_fault_count),
        .if_pipe_stall_cycle(if_pipe_stall_cycle),
        .if_pipe_icache_miss_count(if_pipe_icache_miss_count),
        .if_pipe_icache_replay_count(if_pipe_icache_replay_count),
        .lsu_data_req_count(lsu_mmu_data_req_count),
        .lsu_data_resp_count(lsu_mmu_data_resp_count),
        .lsu_uncached_req_count(lsu_mmu_uncached_req_count),
        .lsu_pipe_issue_count(lsu_pipe_issue_count),
        .lsu_pipe_resp_count(lsu_pipe_resp_count),
        .lsu_pipe_epoch_drop_count(lsu_pipe_epoch_drop_count),
        .lsu_pipe_dtlb_hit_count(lsu_pipe_dtlb_hit_count),
        .lsu_pipe_dtlb_miss_count(lsu_pipe_dtlb_miss_count),
        .lsu_pipe_replay_count(lsu_pipe_replay_count),
        .lsu_pipe_fault_count(lsu_pipe_fault_count),
        .lsu_pipe_stall_cycle(lsu_pipe_stall_cycle),
        .lsu_pipe_dcache_hit_count(lsu_pipe_dcache_hit_count),
        .lsu_pipe_dcache_miss_count(lsu_pipe_dcache_miss_count),
        .lsu_pipe_store_hit_count(lsu_pipe_store_hit_count),
        .lsu_pipe_load_hit_count(lsu_pipe_load_hit_count),
        .lsu_pipe_slow_fallback_count(lsu_pipe_slow_fallback_count),
        .lsu_pipe_load_miss_replay_count(lsu_pipe_load_miss_replay_count),
        .lsu_pipe_store_miss_replay_count(lsu_pipe_store_miss_replay_count),
        .lsu_pipe_direct_uncached_count(lsu_pipe_direct_uncached_count),
        .lsu_pipe_direct_non_dtlb_hit_count(lsu_pipe_direct_non_dtlb_hit_count),
        .lsu_pipe_direct_perm_fault_count(lsu_pipe_direct_perm_fault_count),
        .lsu_pipe_direct_cross_page_count(lsu_pipe_direct_cross_page_count),
        .lsu_pipe_direct_fast_block_count(lsu_pipe_direct_fast_block_count),
        .lsu_pipe_direct_fast_block_atomic_count(lsu_pipe_direct_fast_block_atomic_count),
        .lsu_pipe_direct_fast_block_misaligned_count(lsu_pipe_direct_fast_block_misaligned_count),
        .lsu_pipe_direct_fast_block_exception_count(lsu_pipe_direct_fast_block_exception_count),
        .lsu_pipe_direct_fast_block_phase2_count(lsu_pipe_direct_fast_block_phase2_count),
        .lsu_pipe_direct_fast_block_other_count(lsu_pipe_direct_fast_block_other_count),
        .lsu_pipe_direct_other_count(lsu_pipe_direct_other_count),
        .lsu_pipe_hit_latency_sum(lsu_pipe_hit_latency_sum),
        .lsu_pipe_hit_latency_count(lsu_pipe_hit_latency_count),
        .lsu_pipe_hit_latency_max(lsu_pipe_hit_latency_max),
        .lsu_pipe_load_hit_latency_sum(lsu_pipe_load_hit_latency_sum),
        .lsu_pipe_load_hit_latency_count(lsu_pipe_load_hit_latency_count),
        .lsu_pipe_load_hit_latency_max(lsu_pipe_load_hit_latency_max),
        .lsu_pipe_store_hit_latency_sum(lsu_pipe_store_hit_latency_sum),
        .lsu_pipe_store_hit_latency_count(lsu_pipe_store_hit_latency_count),
        .lsu_pipe_store_hit_latency_max(lsu_pipe_store_hit_latency_max),
        .lsu_pipe_slow_fallback_latency_sum(lsu_pipe_slow_fallback_latency_sum),
        .lsu_pipe_slow_fallback_latency_count(lsu_pipe_slow_fallback_latency_count),
        .lsu_pipe_slow_fallback_latency_max(lsu_pipe_slow_fallback_latency_max),
        .lsu_pipe_slow_direct_latency_sum(lsu_pipe_slow_direct_latency_sum),
        .lsu_pipe_slow_direct_latency_count(lsu_pipe_slow_direct_latency_count),
        .lsu_pipe_slow_direct_latency_max(lsu_pipe_slow_direct_latency_max),
        .lsu_pipe_slow_replay_latency_sum(lsu_pipe_slow_replay_latency_sum),
        .lsu_pipe_slow_replay_latency_count(lsu_pipe_slow_replay_latency_count),
        .lsu_pipe_slow_replay_latency_max(lsu_pipe_slow_replay_latency_max),
        .icache_req_wait_cycle(icache_stat_req_wait_cycle),
        .icache_hit_resp_wait_cycle(icache_stat_hit_resp_wait_cycle),
        .icache_miss_wait_cycle(icache_stat_miss_wait_cycle),
        .icache_uncached_access(icache_stat_uncached_access),
        .dcache_req_wait_cycle(dcache_stat_req_wait_cycle),
        .dcache_hit_resp_wait_cycle(dcache_stat_hit_resp_wait_cycle),
        .dcache_miss_wait_cycle(dcache_stat_miss_wait_cycle),
        .dcache_uncached_access(dcache_stat_uncached_access),
        .dcache_writeback_cycle(dcache_stat_writeback_cycle),
        .branch_redirect_wait_cycle(branch_stat_redirect_wait_cycle),
        .branch_redirect_count(branch_stat_redirect_count),
        .branch_mispredict_count(branch_stat_mispredict_count),
        .load_use_stall_cycle(pipe_stat_load_use_stall_cycle),
        .id_reg_hazard_cycle(pipe_stat_id_reg_hazard_cycle),
        .ms_block_cycle(pipe_stat_ms_block_cycle)
    );
`endif

`ifdef NPC_INSTR_STAT
    InstrStat u_instr_stat(
        .clk(clk),
        .rst_n(rst_n),
        .commit_valid(ws_valid),
        .commit_instr(ws_instr),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal)
    );
`endif

`ifdef NPC_CACHE_STAT
    CacheStat #(
        .ICACHE_MISS_PENALTY(ICACHE_MISS_PENALTY),
        .DCACHE_MISS_PENALTY(DCACHE_MISS_PENALTY)
    ) u_cache_stat(
        .clk(clk),
        .rst_n(rst_n),
        .commit_valid(ws_valid),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal),
        .icache_access(icache_stat_access),
        .icache_hit(icache_stat_hit),
        .icache_miss(icache_stat_miss),
        .icache_refill_req(icache_stat_refill_req),
        .icache_refill_resp(icache_stat_refill_resp),
        .icache_refill_bypass(icache_stat_refill_bypass),
        .icache_req_wait_cycle(icache_stat_req_wait_cycle),
        .icache_hit_resp_wait_cycle(icache_stat_hit_resp_wait_cycle),
        .icache_miss_wait_cycle(icache_stat_miss_wait_cycle),
        .icache_uncached_access(icache_stat_uncached_access),
        .icache_pipe_req_valid_cycle(icache_pipe_req_valid_cycle),
        .icache_pipe_req_ready_cycle(icache_pipe_req_ready_cycle),
        .icache_pipe_req_fire_cycle(icache_pipe_req_fire_cycle),
        .icache_pipe_req_valid_not_ready_cycle(icache_pipe_req_valid_not_ready_cycle),
        .icache_pipe_resp_valid_cycle(icache_pipe_resp_valid_cycle),
        .icache_pipe_resp_ready_cycle(icache_pipe_resp_ready_cycle),
        .icache_pipe_resp_fire_cycle(icache_pipe_resp_fire_cycle),
        .icache_pipe_data_valid_cycle(icache_pipe_data_valid_cycle),
        .icache_pipe_resp_block_cycle(icache_pipe_resp_block_cycle),
        .icache_pipe_ready_block_state_cycle(icache_pipe_ready_block_state_cycle),
        .icache_pipe_ready_block_data_cycle(icache_pipe_ready_block_data_cycle),
        .icache_pipe_ready_block_resp_cycle(icache_pipe_ready_block_resp_cycle),
        .icache_pipe_ready_block_cpu_cycle(icache_pipe_ready_block_cpu_cycle),
        .icache_pipe_ready_block_maint_cycle(icache_pipe_ready_block_maint_cycle),
        .icache_pipe_state_idle_cycle(icache_pipe_state_idle_cycle),
        .icache_pipe_state_refill_cycle(icache_pipe_state_refill_cycle),
        .icache_pipe_state_uncached_cycle(icache_pipe_state_uncached_cycle),
        .icache_pipe_hit_fire_cycle(icache_pipe_hit_fire_cycle),
        .icache_pipe_miss_fire_cycle(icache_pipe_miss_fire_cycle),
        .icache_pipe_refill_busy_cycle(icache_pipe_refill_busy_cycle),
        .icache_pipe_resp_fifo_full_cycle(icache_pipe_resp_fifo_full_cycle),
        .if_pipe_epoch_drop_count(if_pipe_epoch_drop_count),
        .dcache_access(dcache_stat_access),
        .dcache_load_access(dcache_stat_load_access),
        .dcache_store_access(dcache_stat_store_access),
        .dcache_load_hit(dcache_stat_load_hit),
        .dcache_load_miss(dcache_stat_load_miss),
        .dcache_store_hit(dcache_stat_store_hit),
        .dcache_store_miss(dcache_stat_store_miss),
        .dcache_refill_req(dcache_stat_refill_req),
        .dcache_refill_resp(dcache_stat_refill_resp),
        .dcache_write_req(dcache_stat_write_req),
        .dcache_write_resp(dcache_stat_write_resp),
        .dcache_refill_ld_bypass(dcache_stat_refill_ld_bypass),
        .dcache_refill_store_merge(dcache_stat_refill_store_merge),
        .dcache_req_wait_cycle(dcache_stat_req_wait_cycle),
        .dcache_hit_resp_wait_cycle(dcache_stat_hit_resp_wait_cycle),
        .dcache_miss_wait_cycle(dcache_stat_miss_wait_cycle),
        .dcache_uncached_access(dcache_stat_uncached_access),
        .dcache_writeback_cycle(dcache_stat_writeback_cycle),
        .ibus_req_valid(ibus_req_valid_w),
        .ibus_req_ready(ibus_req_ready),
        .ibus_resp_valid(ibus_resp_valid),
        .ibus_resp_ready(ibus_resp_ready_w),
        .dbus_req_valid(dbus_req_valid),
        .dbus_req_ready(dbus_req_ready),
        .dbus_resp_valid(dbus_resp_valid),
        .dbus_resp_ready(dbus_resp_ready)
    );
`endif

`ifdef NPC_PIPE_STAT
    PipeStat u_pipe_stat(
        .clk(clk),
        .rst_n(rst_n),
        .fs_to_ds_valid(fs_to_ds_valid),
        .if_stall(if_stall),
        .ds_allowin(ds_allowin),
        .ds_to_es_valid(ds_to_es_valid),
        .es_allowin(es_allowin),
        .es_to_ms_valid(es_to_ms_valid),
        .ms_allowin(ms_allowin),
        .ms_to_ws_valid(ms_to_ws_valid),
        .ws_allowin(ws_allowin),
        .id_stage_block(ds_stage_block),
        .id_stage_block_reg_hazard(ds_stage_block_reg_hazard),
        .id_stage_block_csr_hazard(ds_stage_block_csr_hazard),
        .id_stage_block_load_use(ds_stage_block_load_use),
        .id_stage_block_ex_raw(ds_stage_block_ex_raw),
        .id_stage_block_ms_raw(ds_stage_block_ms_raw),
        .id_stage_block_hidden_raw(ds_stage_block_hidden_raw),
        .ex_stage_block(es_stage_block),
        .ex_stage_block_mdu_wait(es_stage_block_mdu_wait),
        .ex_stage_block_redirect_wait(es_stage_block_redirect_wait),
        .ms_stage_block(ms_stage_block),
        .ms_stage_block_req_phase(ms_stage_block_req_phase),
        .ms_stage_block_resp_phase(ms_stage_block_resp_phase),
        .es_mem_wr(es_mem_wr),
        .es_mem_fast_block(es_mem_fwd_dep),
        .ms_fast_req_fire(ms_fast_req_fire_trace),
        .ms_slow_req_fire(ms_slow_req_fire_trace),
        .ms_slow_req_fwd_dep_fire(ms_slow_req_fwd_dep_fire_trace),
        .ms_slow_req_nonfwd_fire(ms_slow_req_nonfwd_fire_trace),
        .commit_valid(ws_valid),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal),
        .stat_load_use_stall_cycle(pipe_stat_load_use_stall_cycle),
        .stat_id_reg_hazard_cycle(pipe_stat_id_reg_hazard_cycle),
        .stat_ms_block_cycle(pipe_stat_ms_block_cycle)
    );

    PipelineCPIStat u_pipeline_cpi_stat(
        .clk(clk),
        .rst_n(rst_n),
        .fs_to_ds_valid(fs_to_ds_valid),
        .if_stall(if_stall),
        .ds_allowin(ds_allowin),
        .ds_to_es_valid(ds_to_es_valid),
        .es_allowin(es_allowin),
        .es_to_ms_valid(es_to_ms_valid),
        .ms_allowin(ms_allowin),
        .ms_to_ws_valid(ms_to_ws_valid),
        .ws_allowin(ws_allowin),
        .es_valid(es_valid),
        .ms_valid(ms_valid),
        .ws_valid(ws_valid),
        .id_stage_block(ds_stage_block),
        .id_stage_block_reg_hazard(ds_stage_block_reg_hazard),
        .id_stage_block_csr_hazard(ds_stage_block_csr_hazard),
        .id_stage_block_load_use(ds_stage_block_load_use),
        .id_stage_block_ex_raw(ds_stage_block_ex_raw),
        .id_stage_block_ms_raw(ds_stage_block_ms_raw),
        .id_stage_block_hidden_raw(ds_stage_block_hidden_raw),
        .ds_stat_uses_rs1(ds_stat_uses_rs1),
        .ds_stat_uses_rs2(ds_stat_uses_rs2),
        .ds_stat_rs1_match_es(ds_stat_rs1_match_es),
        .ds_stat_rs1_match_ms(ds_stat_rs1_match_ms),
        .ds_stat_rs1_match_hidden(ds_stat_rs1_match_hidden),
        .ds_stat_rs1_match_ws(ds_stat_rs1_match_ws),
        .ds_stat_rs2_match_es(ds_stat_rs2_match_es),
        .ds_stat_rs2_match_ms(ds_stat_rs2_match_ms),
        .ds_stat_rs2_match_hidden(ds_stat_rs2_match_hidden),
        .ds_stat_rs2_match_ws(ds_stat_rs2_match_ws),
        .ds_stat_csr_counter_hazard(ds_stat_csr_counter_hazard),
        .ds_stat_rs1_ex_alu_fwd(ds_stat_rs1_ex_alu_fwd),
        .ds_stat_rs2_ex_alu_fwd(ds_stat_rs2_ex_alu_fwd),
        .ds_stat_fwd_load_block(ds_stat_fwd_load_block),
        .ds_stat_fwd_csr_block(ds_stat_fwd_csr_block),
        .ds_stat_fwd_kill_block(ds_stat_fwd_kill_block),
        .ex_stage_block(es_stage_block),
        .ex_stage_block_mdu_wait(es_stage_block_mdu_wait),
        .ex_stage_block_redirect_wait(es_stage_block_redirect_wait),
        .es_result_bypassable(es_result_bypassable),
        .es_datatoreg(es_datatoreg),
        .es_mem_wr(es_mem_wr),
        .es_atomic_en(es_atomic_en),
        .es_csr_wen(es_csr_wen),
        .es_stat_is_mdu(es_stat_is_mdu),
        .es_stat_rs1_mem_alu_fwd(es_stat_rs1_mem_alu_fwd),
        .es_stat_rs2_mem_alu_fwd(es_stat_rs2_mem_alu_fwd),
        .es_stat_rs1_wb_fwd(es_stat_rs1_wb_fwd),
        .es_stat_rs2_wb_fwd(es_stat_rs2_wb_fwd),
        .es_stat_rs1_load_fwd(es_stat_rs1_load_fwd),
        .es_stat_rs2_load_fwd(es_stat_rs2_load_fwd),
        .es_stat_mdu_op(es_stat_mdu_op),
        .es_stat_mdu_req_fire(es_stat_mdu_req_fire),
        .es_stat_mdu_resp_valid(es_stat_mdu_resp_valid),
        .es_stat_mdu_busy(es_stat_mdu_busy),
        .es_stat_mdu_result_ready(es_stat_mdu_result_ready),
        .es_stat_fast_mul(es_stat_fast_mul),
        .es_stat_fast_mul_issue(es_stat_fast_mul_issue),
        .es_stat_fast_mul_resp(fast_mul_resp_wb),
        .es_stat_fast_mul_kill(es_stat_fast_mul_kill),
        .es_stat_fast_mul_flush_drop(es_stat_fast_mul_flush_drop),
        .es_stat_fast_mul_forward(es_stat_fast_mul_forward),
        .es_stat_fast_mul_stall_wait_ready(es_stat_fast_mul_stall_wait_ready),
        .es_stat_old_div_path(es_stat_old_div_path),
        .es_stat_old_rem_path(es_stat_old_rem_path),
        .ms_stage_block(ms_stage_block),
        .ms_stage_block_req_phase(ms_stage_block_req_phase),
        .ms_stage_block_resp_phase(ms_stage_block_resp_phase),
        .ms_stage_block_load(ms_stage_block_load),
        .ms_stage_block_store(ms_stage_block_store),
        .ms_stage_block_req_load(ms_stage_block_req_load),
        .ms_stage_block_req_store(ms_stage_block_req_store),
        .ms_stage_block_resp_load(ms_stage_block_resp_load),
        .ms_stage_block_resp_store(ms_stage_block_resp_store),
        .ms_datatoreg(ms_datatoreg),
        .ms_csr_wen(ms_csr_wen),
        .ms_fwd_valid(ms_fwd_valid),
        .ms_stat_load_visible(ms_stat_load_visible),
        .ms_stat_load_aligned(ms_stat_load_aligned),
        .ms_stat_load_result_ready(ms_stat_load_result_ready),
        .ms_stat_load_fault(ms_stat_load_fault),
        .ms_stat_load_signext_ready(ms_stat_load_signext_ready),
        .ms_stat_load_req_fire(ms_stat_load_req_fire),
        .ms_stat_load_resp_valid(ms_stat_load_resp_valid),
        .ms_stat_load_resp_fire(ms_stat_load_resp_fire),
        .ms_stat_load_data_ready(ms_stat_load_data_ready),
        .ms_stat_load_signext_data_ready(ms_stat_load_signext_data_ready),
        .ms_stat_load_to_wb_valid(ms_stat_load_to_wb_valid),
        .ms_stat_load_split_or_misaligned(ms_stat_load_split_or_misaligned),
        .ms_stat_load_uncached(ms_stat_load_uncached),
        .ms_stat_load_atomic(ms_stat_load_atomic),
        .ms_stat_load_killed(ms_stat_load_killed),
        .ms_stat_hidden_load(ms_stat_hidden_load),
        .ms_stat_load_store_block(ms_stat_load_store_block),
        .ms_stat_load_lsu_pending(ms_stat_load_lsu_pending),
        .ms_stat_mreq_valid(ms_stat_mreq_valid),
        .ms_stat_mreq_is_load(ms_stat_mreq_is_load),
        .ms_stat_mreq_is_store(ms_stat_mreq_is_store),
        .ms_stat_mreq_is_atomic(ms_stat_mreq_is_atomic),
        .ms_stat_mreq_need_mem(ms_stat_mreq_need_mem),
        .ms_stat_mreq_fire(ms_stat_mreq_fire),
        .ms_stat_mreq_misaligned(ms_stat_mreq_misaligned),
        .ms_stat_mreq_split(ms_stat_mreq_split),
        .ms_stat_mreq_fault(ms_stat_mreq_fault),
        .ms_stat_mreq_blocked_by_resp(ms_stat_mreq_blocked_by_resp),
        .ms_stat_mresp_valid(ms_stat_mresp_valid),
        .ms_stat_mresp_is_load(ms_stat_mresp_is_load),
        .ms_stat_mresp_is_store(ms_stat_mresp_is_store),
        .ms_stat_mresp_is_atomic(ms_stat_mresp_is_atomic),
        .ms_stat_mresp_resp_valid(ms_stat_mresp_resp_valid),
        .ms_stat_mresp_resp_fire(ms_stat_mresp_resp_fire),
        .ms_stat_mresp_split(ms_stat_mresp_split),
        .ms_stat_mresp_fault(ms_stat_mresp_fault),
        .ms_stat_store_visible(ms_stat_store_visible),
        .ms_stat_store_req_fire(ms_stat_store_req_fire),
        .ms_stat_store_resp_valid(ms_stat_store_resp_valid),
        .ms_stat_store_resp_fire(ms_stat_store_resp_fire),
        .ms_stat_store_aligned(ms_stat_store_aligned),
        .ms_stat_store_fault(ms_stat_store_fault),
        .ms_stat_store_split_or_misaligned(ms_stat_store_split_or_misaligned),
        .ms_stat_store_uncached(ms_stat_store_uncached),
        .ms_stat_store_atomic(ms_stat_store_atomic),
        .ms_stat_store_killed(ms_stat_store_killed),
        .ms_stat_store_buffer_safe(ms_stat_store_buffer_safe),
        .ms_stat_store_resp_wait(ms_stat_store_resp_wait),
        .ms_stat_single_outstanding_wait(ms_stat_single_outstanding_wait),
        .ms_stat_uncached_wait(ms_stat_uncached_wait),
        .ms_stat_writeback_wait(ms_stat_writeback_wait),
        .stat_exmem_skid_candidate(stat_exmem_skid_candidate),
        .stat_exmem_skid_enqueue(stat_exmem_skid_enqueue),
        .stat_exmem_skid_dequeue(stat_exmem_skid_dequeue),
        .stat_exmem_skid_full_stall(stat_exmem_skid_full_stall),
        .stat_exmem_skid_flush_drop(stat_exmem_skid_flush_drop),
        .stat_exmem_skid_blocked_not_safe(stat_exmem_skid_blocked_not_safe),
        .stat_exmem_skid_blocked_branch(stat_exmem_skid_blocked_branch),
        .stat_exmem_skid_blocked_mem(stat_exmem_skid_blocked_mem),
        .stat_exmem_skid_blocked_csr(stat_exmem_skid_blocked_csr),
        .stat_exmem_skid_blocked_exception(stat_exmem_skid_blocked_exception),
        .stat_exmem_skid_blocked_div(stat_exmem_skid_blocked_div),
        .stat_exmem_skid_blocked_structural(stat_exmem_skid_blocked_structural),
        .stat_exmem_skid_hold_cycles(stat_exmem_skid_hold_cycles),
        .stat_exmem_skid_hold_mem_wait_cycles(stat_exmem_skid_hold_mem_wait_cycles),
        .stat_exmem_skid_dequeue_after_mem_release(stat_exmem_skid_dequeue_after_mem_release),
        .stat_exmem_skid_dequeue_same_cycle_mem_release(stat_exmem_skid_dequeue_same_cycle_mem_release),
        .stat_exmem_skid_dequeue_causes_wb_valid(stat_exmem_skid_dequeue_causes_wb_valid),
        .stat_exmem_skid_valid(stat_exmem_skid_valid),
        .stat_exmem_skid_enqueue_fire(stat_exmem_skid_enqueue_fire),
        .stat_exmem_skid_dequeue_fire(stat_exmem_skid_dequeue_fire),
        .stat_exmem_skid_dequeue_commit_fire(stat_exmem_skid_dequeue_commit_fire),
        .stat_exmem_skid_dequeue_to_mreq_fire(stat_exmem_skid_dequeue_to_mreq_fire),
        .stat_exmem_skid_mem_wait(stat_exmem_skid_mem_wait),
        .stat_exmem_skid_mem_release(stat_exmem_skid_mem_release),
        .store_buffer_enqueue_count(store_buffer_enqueue_count),
        .store_buffer_dequeue_count(store_buffer_dequeue_count),
        .store_buffer_full_stall_count(store_buffer_full_stall_count),
        .store_buffer_drain_req_count(store_buffer_drain_req_count),
        .store_buffer_drain_resp_count(store_buffer_drain_resp_count),
        .store_buffer_drain_wait_count(store_buffer_drain_wait_count),
        .store_buffer_load_forward_count(store_buffer_load_forward_count),
        .store_buffer_load_stall_conflict_count(store_buffer_load_stall_conflict_count),
        .store_buffer_load_stall_buffer_nonempty_count(store_buffer_load_stall_buffer_nonempty_count),
        .store_buffer_fence_drain_wait_count(store_buffer_fence_drain_wait_count),
        .store_buffer_uncached_drain_wait_count(store_buffer_uncached_drain_wait_count),
        .store_buffer_killed_store_block_count(store_buffer_killed_store_block_count),
        .store_buffer_occupancy0_count(store_buffer_occupancy0_count),
        .store_buffer_occupancy1_count(store_buffer_occupancy1_count),
        .store_buffer_occupancy2_count(store_buffer_occupancy2_count),
        .store_buffer_max_occupancy_count(store_buffer_max_occupancy_count),
        .store_buffer_enqueue_occ0_count(store_buffer_enqueue_occ0_count),
        .store_buffer_enqueue_occ1_count(store_buffer_enqueue_occ1_count),
        .store_buffer_enqueue_full_count(store_buffer_enqueue_full_count),
        .dhitopt_candidate_count(dhitopt_candidate_count),
        .dhitopt_success_count(dhitopt_success_count),
        .dhitopt_fallback_count(dhitopt_fallback_count),
        .dhitopt_block_store_buffer_count(dhitopt_block_store_buffer_count),
        .dhitopt_block_uncached_count(dhitopt_block_uncached_count),
        .dhitopt_block_fault_count(dhitopt_block_fault_count),
        .dhitopt_block_miss_count(dhitopt_block_miss_count),
        .dhitopt_block_alignment_count(dhitopt_block_alignment_count),
        .dhitopt_unknown_count(dhitopt_unknown_count),
        .hidden_mreq_datatoreg(hidden_mreq_datatoreg),
        .hidden_mreq_mem_wr(hidden_mreq_mem_wr),
        .hidden_mreq_csr_wen(hidden_mreq_csr_wen),
        .ws_stat_datatoreg(ws_stat_datatoreg),
        .ws_stat_mem_op(ws_stat_mem_op),
        .ws_csr_wen(ws_csr_wen),
        .redirect_flush_valid(redirect_flush_valid),
        .redirect_clear_valid(redirect_clear_valid),
        .stop_clear_valid(stop_clear_valid),
        .trap_redirect_valid(trap_redirect_valid),
        .fencei_start(fencei_start),
        .vm_flush_start(vm_flush_start),
        .fencei_maint_active(fencei_maint_active),
        .ibus_req_valid(ibus_req_valid_w),
        .ibus_req_ready(ibus_req_ready),
        .ibus_resp_valid(ibus_resp_valid),
        .ibus_resp_ready(ibus_resp_ready_w),
        .dbus_req_valid(dbus_req_valid),
        .dbus_req_ready(dbus_req_ready),
        .dbus_resp_valid(dbus_resp_valid),
        .dbus_resp_ready(dbus_resp_ready),
        .branch_redirect_wait_cycle(branch_stat_redirect_wait_cycle),
        .icache_req_wait_cycle(icache_stat_req_wait_cycle),
        .icache_hit_resp_wait_cycle(icache_stat_hit_resp_wait_cycle),
        .icache_miss_wait_cycle(icache_stat_miss_wait_cycle),
        .dcache_req_wait_cycle(dcache_stat_req_wait_cycle),
        .dcache_hit_resp_wait_cycle(dcache_stat_hit_resp_wait_cycle),
        .dcache_miss_wait_cycle(dcache_stat_miss_wait_cycle),
        .dcache_uncached_access(dcache_stat_uncached_access),
        .dcache_writeback_cycle(dcache_stat_writeback_cycle),
        .if_pipe_epoch_drop_count(if_pipe_epoch_drop_count),
        .if_pipe_stall_cycle(if_pipe_stall_cycle),
        .if_pipe_icache_miss_count(if_pipe_icache_miss_count),
        .if_stat_fs_valid(if_stat_fs_valid),
        .if_stat_queue_count(if_stat_queue_count),
        .if_stat_fetch_room(if_stat_fetch_room),
        .if_stat_req_fire(if_stat_req_fire),
        .if_stat_resp_fire(if_stat_resp_fire),
        .if_stat_resp_accept(if_stat_resp_accept),
        .if_stat_resp_drop(if_stat_resp_drop),
        .if_stat_bypass_direct(if_stat_bypass_direct),
        .if_stat_waiting_resp(if_stat_waiting_resp),
        .if_stat_drop_resp(if_stat_drop_resp),
        .if_stat_fs_pop(if_stat_fs_pop),
        .if_stat_resp_enq(if_stat_resp_enq),
        .if_stat_queue_full(if_stat_queue_full),
        .if_stat_resp_block(if_stat_resp_block),
        .if_pipe_stat_outstanding(if_pipe_stat_outstanding),
        .if_pipe_stat_replay_valid(if_pipe_stat_replay_valid),
        .if_pipe_stat_ptw_busy(if_pipe_stat_ptw_busy),
        .if_pipe_stat_req_valid(if_pipe_stat_req_valid),
        .if_pipe_stat_req_ready(if_pipe_stat_req_ready),
        .if_pipe_stat_resp_current(if_pipe_stat_resp_current),
        .if_pipe_stat_resp_stale(if_pipe_stat_resp_stale),
        .if_pipe_stat_lower_req_valid(if_pipe_stat_lower_req_valid),
        .if_pipe_stat_lower_req_ready(if_pipe_stat_lower_req_ready),
        .if_pipe_stat_lower_resp_valid(if_pipe_stat_lower_resp_valid),
        .if_pipe_stat_lower_resp_ready(if_pipe_stat_lower_resp_ready),
        .icache_pipe_resp_valid(ibus_icache_pipe_resp_valid),
        .icache_pipe_resp_ready(ibus_icache_pipe_resp_ready),
        .icache_pipe_resp_fifo_full_cycle(icache_pipe_resp_fifo_full_cycle),
        .commit_valid(ws_valid),
        .commit_is_ebreak(commit_is_ebreak),
        .commit_illegal(ws_illegal)
    );
`endif
`endif

    task print_stats;
        begin
`ifdef NPC_USE_DPI
`ifdef NPC_BRANCH_STAT
            u_branch_stat.print_stats();
`endif
`ifdef NPC_MMU_STAT
            u_mmu_stat.print_stats();
`endif
`ifdef NPC_HIT_PATH_STAT
            u_hit_path_stat.print_stats();
`endif
`ifdef NPC_INSTR_STAT
            u_instr_stat.print_stats();
`endif
`ifdef NPC_CACHE_STAT
            u_cache_stat.print_stats();
`endif
`ifdef NPC_PIPE_STAT
            u_pipeline_cpi_stat.print_stats();
`endif
`endif
        end
    endtask
endmodule
