#!/usr/bin/env python3
"""Build the ignored, profile-matched NEMU difftest bundles.

NEMU is never copied into the public Git tree.  The script resolves the
workbench commit recorded in delivery/difftest/nemu_profiles.json, extracts
only its ``nemu`` subtree into flows/local, builds a SHARE interpreter, and
compiles the MIT public ABI adapter next to the raw reference library.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
from typing import Any, Dict, Iterable, Mapping


def find_root() -> Path:
    here = Path(__file__).resolve()
    for candidate in (here.parent, *here.parents):
        if (candidate / "sim/adapters/nemu_public_adapter.cpp").is_file() and (
            (candidate / "Kconfig").is_file()
            or (candidate / "control/Kconfig").is_file()
        ):
            return candidate
    raise SystemExit("cannot locate public NPC root")


ROOT = find_root()
METADATA = ROOT / "delivery/difftest/nemu_profiles.json"
ADAPTER_SOURCE = ROOT / "sim/adapters/nemu_public_adapter.cpp"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def run(command: Iterable[str], cwd: Path, env: Mapping[str, str] | None = None) -> None:
    rendered = " ".join(str(item) for item in command)
    print("[nemu-difftest] " + rendered, flush=True)
    subprocess.run(list(command), cwd=str(cwd), env=dict(env) if env else None,
                   check=True)


def git_output(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=str(repo), text=True).strip()


def safe_extract(archive: tarfile.TarFile, destination: Path) -> None:
    for member in archive:
        name = member.name
        relative = Path(name)
        if relative.is_absolute() or ".." in relative.parts:
            raise SystemExit("unsafe NEMU archive member: " + name)
        # `git archive COMMIT:nemu` normally prefixes entries with `nemu/`.
        # Accept both forms so the exporter remains compatible with Git
        # versions that elide the pathspec prefix.
        if relative.parts and relative.parts[0] == "nemu":
            relative = Path(*relative.parts[1:])
        if not relative.parts:
            continue
        target = destination / relative
        if member.isdir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if not member.isfile():
            raise SystemExit("unsupported NEMU archive member: " + name)
        source = archive.extractfile(member)
        if source is None:
            raise SystemExit("cannot read NEMU archive member: " + name)
        with target.open("wb") as output:
            shutil.copyfileobj(source, output)
        target.chmod(member.mode & 0o777 or 0o644)


def extract_nemu(repo: Path, commit: str, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    process = subprocess.Popen(
        ["git", "archive", "--format=tar", f"{commit}:nemu"],
        cwd=str(repo), stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    assert process.stdout is not None
    try:
        with tarfile.open(fileobj=process.stdout, mode="r|") as archive:
            safe_extract(archive, destination)
    finally:
        process.stdout.close()
    stderr = process.stderr.read().decode("utf-8", errors="replace") if process.stderr else ""
    status = process.wait()
    if status != 0:
        raise SystemExit(f"git archive failed for {commit}: {stderr.strip()}")


def write_ref_defconfig(source: Path) -> str:
    name = "npc_public_riscv32_share_defconfig"
    config = """# Generated by prepare_nemu_difftest.py; local and ignored.
CONFIG_ISA_riscv=y
CONFIG_ENGINE_INTERPRETER=y
CONFIG_MODE_SYSTEM=y
CONFIG_TARGET_SHARE=y
CONFIG_CC_GCC=y
CONFIG_CC_O2=y
CONFIG_CC_OPT=\"-O2\"
# CONFIG_TRACE is not set
# CONFIG_WATCHPOINT is not set
# CONFIG_DIFFTEST is not set
CONFIG_RISCV_ILLEGAL_TRAP=y
CONFIG_RISCV_EBREAK_TRAP=y
CONFIG_RISCV_UNSUPPORTED_CSR_TRAP=y
CONFIG_RISCV_TESTS_TOHOST_MONITOR=y
CONFIG_RISCV_MISALIGNED_DATA=y
# CONFIG_RISCV_TRIGGER_ENABLE is not set
CONFIG_MSIZE=0x10000000
CONFIG_PMEM_GARRAY=y
# CONFIG_DEVICE is not set
CONFIG_RT_CHECK=y
"""
    path = source / "configs" / f"{name}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config, encoding="utf-8")
    return name


def build_raw_nemu(source: Path, jobs: int) -> Path:
    source_abs = source.resolve()
    target = write_ref_defconfig(source)
    env = os.environ.copy()
    env["NEMU_HOME"] = str(source_abs)
    run(["make", "-s", "-C", str(source_abs), f"NEMU_HOME={source_abs}", target],
        source, env)
    # The historical NEMU source keeps the SDB objects in the shared build
    # even when TARGET_SHARE is selected.  Link its readline symbols explicitly
    # so dlopen() is deterministic instead of leaving unresolved add_history /
    # readline references in the raw .so.
    run(["make", "-C", str(source_abs), f"NEMU_HOME={source_abs}", "SHARE=1",
         "LIBS=-lreadline -ldl", f"-j{jobs}"], source, env)
    raw = source / "build/riscv32-nemu-interpreter-so"
    if not raw.is_file():
        raise SystemExit("NEMU SHARE build did not produce " + str(raw))
    return raw


def compile_adapter(root: Path, destination: Path, profile: str,
                    record: Mapping[str, Any], raw_name: str) -> Path:
    output = destination / "npc-public-nemu-adapter.so"
    defines = [
        f'-DNPC_NEMU_PROFILE_ID="{profile}"',
        f'-DNPC_NEMU_RAW_BASENAME="{raw_name}"',
        f'-DNPC_NEMU_SOURCE_COMMIT="{record["workbench_commit"]}"',
        f'-DNPC_NEMU_TREE_SHA256="{record["nemu_tree"]}"',
        f'-DNPC_NEMU_ENABLE_A={1 if record.get("enable_a") else 0}',
        f'-DNPC_NEMU_ENABLE_S={1 if record.get("enable_s") else 0}',
        f'-DNPC_NEMU_ENABLE_SV32={1 if record.get("enable_sv32") else 0}',
        f'-DNPC_NEMU_DEBUG_SENTINEL={1 if profile == "rv32im_ooo_4k" else 0}',
    ]
    command = [
        os.environ.get("CXX", "g++"), "-std=c++17", "-O2", "-fPIC",
        "-shared", "-Wall", "-Wextra", *defines,
        "-I", str(root / "sim/include"), "-o", str(output),
        str(ADAPTER_SOURCE), "-ldl",
    ]
    run(command, root)
    if not output.is_file():
        raise SystemExit("adapter build did not produce " + str(output))
    return output


def build_profile(root: Path, source_repo: Path, profile: str,
                  record: Mapping[str, Any], metadata: Mapping[str, Any],
                  force: bool, jobs: int) -> Dict[str, Any]:
    base = root / "flows/local/nemu" / profile
    if base.exists():
        if not force:
            manifest = base / "manifest.json"
            if manifest.is_file():
                existing = json.loads(manifest.read_text(encoding="utf-8"))
                if (existing.get("profile") == profile and
                    existing.get("workbench_commit") == record["workbench_commit"] and
                    existing.get("nemu_tree") == record["nemu_tree"] and
                    existing.get("config_contract") == metadata["build_contract"] and
                    existing.get("adapter_source_sha256") == sha256_file(ADAPTER_SOURCE)):
                    adapter = base / str(existing.get("adapter_library", ""))
                    raw = base / str(existing.get("raw_library", ""))
                    if (adapter.is_file() and raw.is_file() and
                        sha256_file(adapter) == existing.get("adapter_sha256") and
                        sha256_file(raw) == existing.get("raw_sha256")):
                        print(f"[nemu-difftest] existing bundle kept: {base}")
                        return existing
                raise SystemExit(
                    f"local bundle is stale or corrupt: {base}; use --force to rebuild"
                )
            raise SystemExit(f"local bundle exists without manifest: {base}; use --force")
        shutil.rmtree(base)
    source = base / "source"
    commit = str(record["workbench_commit"])
    resolved = git_output(source_repo, "rev-parse", "--verify", f"{commit}^{{commit}}")
    if resolved != commit:
        raise SystemExit(f"resolved commit differs for {profile}: {resolved} != {commit}")
    tree = git_output(source_repo, "rev-parse", f"{commit}:nemu")
    if tree != str(record["nemu_tree"]):
        raise SystemExit(f"NEMU tree drift for {profile}: {tree} != {record['nemu_tree']}")
    extract_nemu(source_repo, commit, source)
    raw = build_raw_nemu(source, jobs)
    raw_name = str(metadata["raw_library"])
    raw_copy = base / raw_name
    shutil.copy2(raw, raw_copy)
    adapter = compile_adapter(root, base, profile, record, raw_name)
    config_path = source / "configs/npc_public_riscv32_share_defconfig"
    manifest: Dict[str, Any] = {
        "schema": "npc-riscv-open/local-nemu-bundle-v1",
        "profile": profile,
        "source_ref": record["source_ref"],
        "workbench_commit": commit,
        "nemu_tree": tree,
        "isa": record["isa"],
        "adapter_abi": 2,
        "raw_library": raw_name,
        "adapter_library": str(metadata["adapter_library"]),
        "raw_sha256": sha256_file(raw_copy),
        "adapter_sha256": sha256_file(adapter),
        "adapter_source_sha256": sha256_file(ADAPTER_SOURCE),
        "defconfig_sha256": sha256_file(config_path),
        "config_contract": metadata["build_contract"],
    }
    (base / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    rows = [
        f"{manifest['raw_sha256']}  {raw_name}",
        f"{manifest['adapter_sha256']}  {manifest['adapter_library']}",
        f"{manifest['defconfig_sha256']}  source/configs/npc_public_riscv32_share_defconfig",
    ]
    (base / "SHA256SUMS").write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"[nemu-difftest] ready {profile}: raw={manifest['raw_sha256']} adapter={manifest['adapter_sha256']}")
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--source-repo", type=Path,
                        default=os.environ.get("NPC_NEMU_SOURCE_REPO", ""))
    parser.add_argument("--profile", choices=(
        "rv32im_single_perf", "rv32ima_sv32_linux", "rv32im_ooo_4k", "all"),
        default="all")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--jobs", type=int, default=max(1, min(8, os.cpu_count() or 1)))
    args = parser.parse_args(argv)
    root = args.root.resolve()
    metadata_path = root / "delivery/difftest/nemu_profiles.json"
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    source_repo = Path(args.source_repo).resolve() if str(args.source_repo) else None
    if source_repo is None or not (source_repo / ".git").exists():
        raise SystemExit("set NPC_NEMU_SOURCE_REPO to the workbench Git repository")
    profiles = metadata["profiles"]
    selected = list(profiles) if args.profile == "all" else [args.profile]
    results = {}
    for profile in selected:
        results[profile] = build_profile(root, source_repo, profile, profiles[profile],
                                         metadata, args.force, max(1, args.jobs))
    print(json.dumps({"schema": "npc-riscv-open/local-nemu-index-v1",
                      "profiles": results}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
